### ISSUE TITLE
[v1.18.0] FTBFS: libOpenModelicaCompiler.so: undefined reference to `NFType_NFType_ENUMERATION__ANY(double,...)(short, char)'

### ISSUE THREAD

**Issue by jschueller** [OpenModelica/OpenModelica#7922]
### Description

libOpenModelicaCompiler.so fails to build

### Steps to Reproduce

```
git clone https://github.com/OpenModelica/OpenModelica.git
cd OpenModelica
git checkout v1.18.0
git submodule init && git submodule sync --recursive && git submodule -q update --init --recursive
cd OMCompiler
autoconf
CFLAGS="-fno-tree-vrp" ./configure --prefix=/usr/local
make
```

### Expected Behavior

make command succeeds 

### Screenshots

```
gcc -shared -Wl,-z,origin -Wl,-rpath,'$ORIGIN/../lib/x86_64-linux-gnu/omc' -Wl,-rpath,'$ORIGIN'  -o /tmp/OpenModelica/OMCompiler/build/lib/x86_64-linux-gnu/omc/libOpenModelicaCompiler.so build/ZeroCrossings.o build/UnitChecker.o build/UnitAbsynBuilder.o build/SimCodeUtil.o build/SimCodeMain.o build/SimCode.o build/RewriteRules.o build/Refactor.o build/PackageManagement.o build/NFUnitCheck.o build/NFSCodeFlatten.o build/NFInstDump.o build/NFApi.o build/MidCode.o build/InstStateMachineUtil.o build/FUnitCheck.o build/FGraphStream.o build/ExpandableArray.o build/DumpGraphviz.o build/DAEToMid.o build/CodegenMidToC.o build/CevalScriptOMSimulator.o build/CevalScriptBackend.o build/BackendDAEUtil.o build/BackendDAECreate.o build/Autoconf.o build/AbsynJLDumpTpl.o build/ZeroMQ.o build/VarTransform.o build/Util.o build/Testsuite.o build/System.o build/Socket.o build/StringUtil.o build/StackOverflow.o build/Settings.o build/SemanticVersion.o build/Print.o build/Pointer.o build/Mutable.o build/ModelicaExternalC.o build/List.o build/Lapack.o build/IOStream.o build/IOStreamExt.o build/HashTableStringToProgram.o build/HashTableStringToPath.o build/HashTableExpToIndex.o build/HashTable.o build/HashTableCrToExpOption.o build/HashTableCrIListArray.o build/HashTableCrILst.o build/HashTableCrefSimVar.o build/HashTableCG.o build/HashTable5.o build/HashTable3.o build/HashTable2.o build/HashSetString.o build/HashSetExp.o build/HashSet.o build/GraphStreamExt.o build/GraphStream.o build/Graph.o build/Gettext.o build/GC.o build/FlagsUtil.o build/Flags.o build/ExecStat.o build/ErrorTypes.o build/Error.o build/ErrorExt.o build/DynLoad.o build/DoubleEnded.o build/Debug.o build/Corba.o build/Config.o build/ClockIndexes.o build/BaseHashSet.o build/BaseHashTable.o build/BaseAvlSet.o build/BaseAvlTree.o build/AvlTreeCRToInt.o build/AvlTreeStringString.o build/AvlSetString.o build/AvlSetPath.o build/AvlSetCR.o build/Array.o build/Main.o build/Global.o build/Unparsing.o build/TplParser.o build/Tpl.o build/TplMain.o build/TplCodegen.o build/TplAbsyn.o build/SCodeDumpTpl.o build/GenerateAPIFunctionsTpl.o build/ExpressionDumpTpl.o build/DAEDumpTpl.o build/CodegenUtil.o build/CodegenCFunctions.o build/AbsynDumpTpl.o build/InteractiveUtil.o build/SymbolTable.o build/StaticScript.o build/Interactive.o build/GlobalScriptUtil.o build/GlobalScriptDump.o build/GlobalScript.o build/CevalScript.o build/SimCodeVar.o build/SimCodeFunctionUtil.o build/SimCodeFunction.o build/HpcOmSimCode.o build/BackendDAE.o build/FVisit.o build/FTraverse.o build/FResolve.o build/FNode.o build/FMod.o build/FLookup.o build/FGraphBuildEnv.o build/FGraphBuild.o build/FGraph.o build/FExpand.o build/FCore.o build/FBuiltin.o build/ValuesUtil.o build/Values.o build/UnitParserExt.o build/UnitAbsyn.o build/Types.o build/StateMachineFlatten.o build/Static.o build/SCodeUtil.o build/SCodeInstUtil.o build/SCodeDump.o build/SCode.o build/PrefixUtil.o build/Patternm.o build/ParserExt.o build/Parser.o build/OperatorOverloading.o build/NFInstUtil.o build/Mod.o build/MMath.o build/MetaUtil.o build/Lookup.o build/InstTypes.o build/InstSection.o build/InstExtends.o build/InstUtil.o build/InstMeta.o build/InstHashTable.o build/InstFunction.o build/InstBinding.o build/InstDAE.o build/InstVar.o build/Inst.o build/InnerOuter.o build/Inline.o build/Graphviz.o build/ExpressionSimplifyTypes.o build/ExpressionSimplify.o build/Expression.o build/ExpressionDump.o build/ElementSource.o build/Dump.o build/DAEUtil.o build/DAE.o build/DAEDump.o build/Constants.o build/ConnectUtil.o build/ConnectionGraph.o build/ComponentReference.o build/ClassLoader.o build/ClassInf.o build/Ceval.o build/CevalFunction.o build/Builtin.o build/BackendInterface.o build/Algorithm.o build/AbsynUtil.o build/AbsynToSCode.o build/Absyn.o build/File.o build/ZeroCrossings_records.o build/UnitChecker_records.o build/UnitAbsynBuilder_records.o build/SimCodeUtil_records.o build/SimCodeMain_records.o build/SimCode_records.o build/RewriteRules_records.o build/Refactor_records.o build/PackageManagement_records.o build/NFUnitCheck_records.o build/NFSCodeFlatten_records.o build/NFInstDump_records.o build/NFApi_records.o build/MidCode_records.o build/InstStateMachineUtil_records.o build/FUnitCheck_records.o build/FGraphStream_records.o build/ExpandableArray_records.o build/DumpGraphviz_records.o build/DAEToMid_records.o build/CodegenMidToC_records.o build/CevalScriptOMSimulator_records.o build/CevalScriptBackend_records.o build/BackendDAEUtil_records.o build/BackendDAECreate_records.o build/Autoconf_records.o build/AbsynJLDumpTpl_records.o build/ZeroMQ_records.o build/VarTransform_records.o build/Util_records.o build/Testsuite_records.o build/System_records.o build/Socket_records.o build/StringUtil_records.o build/StackOverflow_records.o build/Settings_records.o build/SemanticVersion_records.o build/Print_records.o build/Pointer_records.o build/Mutable_records.o build/ModelicaExternalC_records.o build/List_records.o build/Lapack_records.o build/IOStream_records.o build/IOStreamExt_records.o build/HashTableStringToProgram_records.o build/HashTableStringToPath_records.o build/HashTableExpToIndex_records.o build/HashTable_records.o build/HashTableCrToExpOption_records.o build/HashTableCrIListArray_records.o build/HashTableCrILst_records.o build/HashTableCrefSimVar_records.o build/HashTableCG_records.o build/HashTable5_records.o build/HashTable3_records.o build/HashTable2_records.o build/HashSetString_records.o build/HashSetExp_records.o build/HashSet_records.o build/GraphStreamExt_records.o build/GraphStream_records.o build/Graph_records.o build/Gettext_records.o build/GC_records.o build/FlagsUtil_records.o build/Flags_records.o build/ExecStat_records.o build/ErrorTypes_records.o build/Error_records.o build/ErrorExt_records.o build/DynLoad_records.o build/DoubleEnded_records.o build/Debug_records.o build/Corba_records.o build/Config_records.o build/ClockIndexes_records.o build/BaseHashSet_records.o build/BaseHashTable_records.o build/BaseAvlSet_records.o build/BaseAvlTree_records.o build/AvlTreeCRToInt_records.o build/AvlTreeStringString_records.o build/AvlSetString_records.o build/AvlSetPath_records.o build/AvlSetCR_records.o build/Array_records.o build/Main_records.o build/Global_records.o build/Unparsing_records.o build/TplParser_records.o build/Tpl_records.o build/TplMain_records.o build/TplCodegen_records.o build/TplAbsyn_records.o build/SCodeDumpTpl_records.o build/GenerateAPIFunctionsTpl_records.o build/ExpressionDumpTpl_records.o build/DAEDumpTpl_records.o build/CodegenUtil_records.o build/CodegenCFunctions_records.o build/AbsynDumpTpl_records.o build/InteractiveUtil_records.o build/SymbolTable_records.o build/StaticScript_records.o build/Interactive_records.o build/GlobalScriptUtil_records.o build/GlobalScriptDump_records.o build/GlobalScript_records.o build/CevalScript_records.o build/SimCodeVar_records.o build/SimCodeFunctionUtil_records.o build/SimCodeFunction_records.o build/HpcOmSimCode_records.o build/BackendDAE_records.o build/FVisit_records.o build/FTraverse_records.o build/FResolve_records.o build/FNode_records.o build/FMod_records.o build/FLookup_records.o build/FGraphBuildEnv_records.o build/FGraphBuild_records.o build/FGraph_records.o build/FExpand_records.o build/FCore_records.o build/FBuiltin_records.o build/ValuesUtil_records.o build/Values_records.o build/UnitParserExt_records.o build/UnitAbsyn_records.o build/Types_records.o build/StateMachineFlatten_records.o build/Static_records.o build/SCodeUtil_records.o build/SCodeInstUtil_records.o build/SCodeDump_records.o build/SCode_records.o build/PrefixUtil_records.o build/Patternm_records.o build/ParserExt_records.o build/Parser_records.o build/OperatorOverloading_records.o build/NFInstUtil_records.o build/Mod_records.o build/MMath_records.o build/MetaUtil_records.o build/Lookup_records.o build/InstTypes_records.o build/InstSection_records.o build/InstExtends_records.o build/InstUtil_records.o build/InstMeta_records.o build/InstHashTable_records.o build/InstFunction_records.o build/InstBinding_records.o build/InstDAE_records.o build/InstVar_records.o build/Inst_records.o build/InnerOuter_records.o build/Inline_records.o build/Graphviz_records.o build/ExpressionSimplifyTypes_records.o build/ExpressionSimplify_records.o build/Expression_records.o build/ExpressionDump_records.o build/ElementSource_records.o build/Dump_records.o build/DAEUtil_records.o build/DAE_records.o build/DAEDump_records.o build/Constants_records.o build/ConnectUtil_records.o build/ConnectionGraph_records.o build/ComponentReference_records.o build/ClassLoader_records.o build/ClassInf_records.o build/Ceval_records.o build/CevalFunction_records.o build/Builtin_records.o build/BackendInterface_records.o build/Algorithm_records.o build/AbsynUtil_records.o build/AbsynToSCode_records.o build/Absyn_records.o build/File_records.o build/_main_omc.o -L.  -Lbuild/ -L"/tmp/OpenModelica/OMCompiler/build/lib/x86_64-linux-gnu/omc" ../../Parser/libomparse-boot.a /tmp/OpenModelica/OMCompiler/Compiler/runtime/libomcgraphstream.a /tmp/OpenModelica/OMCompiler/Compiler/runtime/libomcbackendruntime.a /tmp/OpenModelica/OMCompiler/Compiler/runtime/libomcruntime-boot.so /tmp/OpenModelica/OMCompiler/3rdParty/libffi/install/lib*/libffi.a  -lOpenModelicaRuntimeC -lModelicaExternalC -lModelicaIO -lModelicaMatIO -lzlib -lomantlr3    -Wl,--no-as-needed -Wl,--disable-new-dtags  -lcurl  -lomcgc  -lpthread -lm -ldl  -lstdc++ -rdynamic  -llpsolve55 -lm -ldl   -luuid -L/usr/local/lib/x86_64-linux-gnu/omc -lmetis  -llapack -lblas   -lzmq
^[[91m/tmp/OpenModelica/OMCompiler/build/lib/x86_64-linux-gnu/omc/libModelicaExternalC.a(ModelicaInternal.o): In function `ModelicaInternal_temporaryFileName':
ModelicaInternal.c:(.text+0x950): warning: the use of `tmpnam' is dangerous, better use `mkstemp'
^[[0mtest ! ".so" = ".dylib" || install_name_tool -id @rpath/libOpenModelicaCompiler.dylib /tmp/OpenModelica/OMCompiler/build/lib/x86_64-linux-gnu/omc/libOpenModelicaCompiler.so
test ! ".so" = ".dylib" || install_name_tool -change libcolamd.dylib @rpath/libcolamd.dylib /tmp/OpenModelica/OMCompiler/build/lib/x86_64-linux-gnu/omc/libOpenModelicaCompiler.so
test ! ".so" = ".dylib" || install_name_tool -change libsuitesparseconfig.dylib @rpath/libsuitesparseconfig.dylib /tmp/OpenModelica/OMCompiler/build/lib/x86_64-linux-gnu/omc/libOpenModelicaCompiler.so
gcc build/_main.o -Wl,-z,origin -Wl,-rpath,'$ORIGIN/../lib/x86_64-linux-gnu/omc' -Wl,-rpath,'$ORIGIN' -fno-tree-vrp -fno-stack-protector -fno-tree-vrp -fPIC  -Wno-parentheses-equality -Wno-unused-variable -Werror=implicit-function-declaration -Werror=incompatible-pointer-types -I/tmp/OpenModelica/OMCompiler/build/include/omc/c -I../Util/  -DADD_METARECORD_DEFINITIONS= -DOMC_BOOTSTRAPPING_STAGE_1 -o build/omc -L"/tmp/OpenModelica/OMCompiler/build/lib/x86_64-linux-gnu/omc" -Wl,-rpath-link,/tmp/OpenModelica/OMCompiler/build/lib/x86_64-linux-gnu/omc -lOpenModelicaCompiler
^[[91m/tmp/OpenModelica/OMCompiler/build/lib/x86_64-linux-gnu/omc/libOpenModelicaCompiler.so: undefined reference to `NFType_NFType_ENUMERATION__ANY(double,...)(short, char)'
```

### Version and OS

- openmodelica v1.18.0
- centos 7 (gcc 8.x from devtoolset 8)

### Additional Context

It is a regression from openmodelica 1.17.0, so I tried git bisect:

```
cf3a725b80887bf52e84af1884492cdbb870161f is the first bad commit
commit cf3a725b80887bf52e84af1884492cdbb870161f
Author: perost <perost86@gmail.com>
Date:   Sun Feb 21 17:14:32 2021 +0100

    Implement external function evaluation with libffi (#7178)
```

indeed https://github.com/OpenModelica/OpenModelica/pull/7178 has modifications in OpenModelicaBootstrappingHeader.h
involving NF* types, which is consistent with the error message

cc @perost

**Comment by sjoelund** [comment]
Use `./configure ... --without-omc`

**Comment by jschueller** [comment]
but I need the omc compiler utility...

**Comment by sjoelund** [comment]
`--without-omc` compiles a new `omc` without using the old one. If you have an old one, not compatible with the new one, it will fail.

**Comment by jschueller** [comment]
oh, I did not have an old one, so its not likely to change the result

**Comment by jschueller** [comment]
I can totally reproduce with this minimal centos docker image:
```
FROM centos:7
MAINTAINER jschueller

RUN yum -y install epel-release && yum -y install centos-release-scl \
 && yum -y install wget git patch zip unzip bzip2 bsdtar perl subversion gettext autoconf automake libtool bison flex make which file \
  blas-devel lapack-devel atlas-devel libxml2-devel libmpc-devel mpfr-devel xz-devel \
  zlib-devel bzip2-devel ncurses-devel sqlite-devel readline-devel libffi-devel \
  java-1.8.0-openjdk expat-devel lpsolve-devel libuuid-devel curl-devel \
  devtoolset-8-gcc devtoolset-8-gcc-c++ devtoolset-8-gcc-gfortran devtoolset-8-binutils cmake3 \
 && ln -s /usr/bin/cmake3 /usr/bin/cmake
ENV PATH=/opt/rh/devtoolset-8/root/usr/bin:$PATH LD_LIBRARY_PATH=/opt/rh/devtoolset-8/root/usr/lib64:/opt/rh/devtoolset-8/root/usr/lib
WORKDIR /tmp

RUN git clone https://github.com/OpenModelica/OpenModelica.git && cd OpenModelica && git checkout v1.18.0 \
 && git submodule init && git submodule sync --recursive && git submodule -q update --init --recursive
RUN cd OpenModelica/OMCompiler && autoconf && CFLAGS="-fno-tree-vrp" ./configure && make -j8
```
Maybe its due to the rpm compilation flags of yours ?

**Comment by rfranke** [comment]
Might be a duplicate of #7884 that was closed without action. It's unfortunate that OpenModelica doesn't compile "out-of-the-box" with default settings, i.e. requires a flag named `--without-omc` for any existing user that just wants to try a new version.

**Comment by jschueller** [comment]
turns out it was my cflags

**Comment by sjoelund** [comment]
> turns out it was my cflags

Fun... Disabling optimization flags makes things stop working? Nice one, GCC...

**Comment by adrpo** [comment]
@sjoelund I think we should make the --without-omc the default configure flag. It might take a while longer to compile but at least it does.
