### ISSUE TITLE
Wrong generated code in 1.19.2

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#9168]
While testing #8938 in the 1.19.2 release, I found that running `Modelica.Mechanics.MultiBody.Examples.Loops.PlanarLoops_analytic` generates broken C code:

PlanarLoops_analytic_02nls.c:50:47: error: invalid operands to binary expression ('real_array' (aka 'struct base_array_s') and 'double')
  }res[0] = sub_alloc_real_array(tmp0, (tmp1) * (sqrt(tmp4)));
                                       ~~~~~~ ^ ~~~~~~~~~~~~
PlanarLoops_analytic_02nls.c:84:6: error: redefinition of 'residualFunc445'
void residualFunc445(void** dataIn, const double* xloc, double* res, const int* iflag)
     ^
PlanarLoops_analytic_02nls.c:10:6: note: previous definition is here
void residualFunc445(void** dataIn, const double* xloc, double* res, const int* iflag)

@mahge, this should be fixed ASAP. Thanks!

**Comment by perost** [comment]
The library testing says the model [works fine](https://libraries.openmodelica.org/branches/master/Modelica_4.0.0/files/Modelica_4.0.0_Modelica.Mechanics.MultiBody.Examples.Loops.PlanarLoops_analytic.sim) though, so perhaps you're using some flag or something that influences it? But it still shouldn't happen of course.

**Comment by mahge** [comment]
If you have checked the generated code, did you by any chance see some variables named `$cse* around the faulty code? I am investigating #9123 and the issues look similar. Something might have changed in how we handle Common Subexpression Elimination. It is generating some invalid types.

**Comment by mahge** [comment]
> The library testing says the model [works fine](https://libraries.openmodelica.org/branches/master/Modelica_4.0.0/files/Modelica_4.0.0_Modelica.Mechanics.MultiBody.Examples.Loops.PlanarLoops_analytic.sim) though, so perhaps you're using some flag or something that influences it? But it still shouldn't happen of course.

Maybe @casella is using something built from the maintenance branch? Maybe something is incomplete there.

**Comment by mahge** [comment]
Yup it is [broken in 1.19](https://libraries.openmodelica.org/branches/v1.19/Modelica_4.0.0/files/Modelica_4.0.0_Modelica.Mechanics.MultiBody.Examples.Loops.PlanarLoops_analytic.err)

**Comment by casella** [comment]
Of course 1.19.2 is taken from the maintenance branch. The master version is fine, and the nighly builds work fine as well. I guess there is some missing cherry-picked commit in the maintenance branch. I'm not sure if this has always been the case with maintenance/v1.19, or if it is a regression introduced at some point. @mahge could you carry out some bisection on that branch? It shouldn't take long, there are not so many commits there - if the first is broken, then it has never been fixed in 1.19 in the first place, otherwise a few bisection runs should easily give the information about the offending commit.

**Comment by casella** [comment]
@mahge, I also tested the original test case of #8772
```modelica
package P
  impure function f // function marked impure to prevent the NF from constant evaluating it.
    output Real a[2] = fill(1.0, 2);
    annotation(Inline=false);
  end f;

  function f2
    input Real a[2];
    output Real b[2] = fill(1.0, 2);
    annotation(Inline=false);
  end f2;

  model M
    parameter Real a[2] = f();
    parameter Real d[2] = b;
    parameter Real b[2] = f2(a);
  end M;
end P;
```
and I get broken C code
```
M_02nls.c:34:10: error: assigning to 'double' from incompatible type 'real_array_t' (aka 'struct base_array_s')
  res[0] = sub_alloc_real_array(omc_P_f2(threadData, tmp0), tmp1);
         ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```
That's a bit weird, this model is supposed to only need three assignments in the right sequence to initialize the parameters, why on Earth are there problems on the nls.c file?

I guess something very basic was broken on the maintenance branch at some point.

**Comment by mahge** [comment]
I think #8933 is missing. It should have been ported when #8981 was ported in #9073. Adding the commit from #8933 fixes this issue for me. 

We need to be extra careful with this cherry-picks and pay attention to the regression tests. Otherwise it is very easy to have broken branches and it will be very hard to localize the issue. I think this would have been difficult to find it you have not noticed that #8772 was broken as well.

**Comment by mahge** [comment]
I will port #8933 to maintenance.

**Comment by casella** [comment]
> We need to be extra careful with this cherry-picks 

Absolutely. Only critical bug fixes. #8938 was a big deal.

> and pay attention to the regression tests. Otherwise it is very easy to have broken branches and it will be very hard to localize the issue. I think this would have been difficult to find it you have not noticed that #8772 was broken as well.

Indeed. Even though somebody else would have found out, eventually 😅 

In fact, I am personally testing that everything we claim works in a bugfix version actually does. St. Thomas' style 😄

**Comment by casella** [comment]
> We need to be extra careful with this cherry-picks and pay attention to the regression tests. Otherwise it is very easy to have broken branches and it will be very hard to localize the issue. I think this would have been difficult to find it you have not noticed that #8772 was broken as well.

On a second thought, I couldn't agree more. The question is: do we have regression reports for the maintenance branches? I'm afraid we don't. @mahge I opened #9182 on that topic, if we already do that please let me know.
