### ISSUE TITLE
SimCode lists parameters additionally as algebraic variables for C++

### ISSUE THREAD

**Issue by rfranke** [OpenModelica/OpenModelica#10693]
### Description

Many examples of Buildings fail with C++ due to duplicate variable declarations. For instance (a small one):
[Buildings.HeatTransfer.Windows.BaseClasses.Examples.TransmittedRadiation](https://libraries.openmodelica.org/branches/cpp/Buildings_latest/files/Buildings_latest_Buildings.HeatTransfer.Windows.BaseClasses.Examples.TransmittedRadiation.err)
```
./OMCppBuildings_latest_Buildings.HeatTransfer.Windows.BaseClasses.Examples.TransmittedRadiation.h:416:41: error: duplicate member '_winTra_P_radDat_P_absExtIrrExtSha_'
    StatArrayDim3<double, 2,11,1, true> _winTra_P_radDat_P_absExtIrrExtSha_;
                                        ^
./OMCppBuildings_latest_Buildings.HeatTransfer.Windows.BaseClasses.Examples.TransmittedRadiation.h:251:41: note: previous declaration is here
    StatArrayDim3<double, 2,11,1, true> _winTra_P_radDat_P_absExtIrrExtSha_;
```
### Steps to Reproduce

```
setCommandLineOptions("-d=dumpSimCode"); getErrorString();
loadFile("modelica-buildings/Buildings/package.mo"); getErrorString();
simulate(Buildings.HeatTransfer.Windows.BaseClasses.Examples.TransmittedRadiation); getErrorString();
```
gives:
```
...
paramVars
----------------------
...
index:169: winTra.radDat.absExtIrrExtSha[1,1,1] (no alias)  initial: Buildings.HeatTransfer.Windows.Functions.glassAbsExteriorIrradiationExteriorShading(winTra.radDat.absExtIrrNoSha, winTra.radDat.traRef, winTra.radDat.traRefShaDev, 2, 1, 11)	arrCref:winTra.radDat.absExtIrrExtSha index:(280) [2,11,1]
...
```
Adding
```
setCommandLineOptions("--simCodeTarget=Cpp"); getErrorString();
```
gives:
```
...
modelInfo:
========================================
algVars (351)
----------------------
...
index:107: winTra.radDat.absExtIrrExtSha[1,1,1] (no alias)  initial: 	arrCref:winTra.radDat.absExtIrrExtSha index:(108) [2,11,1]
...
paramVars
----------------------
...
index:168: winTra.radDat.absExtIrrExtSha (no alias)  initial: 	no arrCref index:(523) [2,11,1]
...
```

### Expected Behavior

SimCode should be the same for C and C++.

### Version and OS

Current nightly build.

**Comment by rfranke** [comment]
`Modelica.Mechanics.MultiBody.Examples.Loops.PlanarLoops_analytic` exhibits the same problem. This means that the error has been newly introduced.

Binary search in the commit history shows that it stopped working with #8933, then raising:
```
function BackendEquation.solveEquation failed w.r.t jointRRR1.n_b[3]
ARRAY_EQUATION: jointRRR1.n_bCREF jointRRR1 [model Modelica.Mechanics.MultiBody.Joints.Assemblies.JointRRR] .n_b [Real[3]] CREFTYPE:Real[3]
...
```
(see also compaint by @casella in the PR). It turned into the current error with #8981:
```
OMCppModelica.Mechanics.MultiBody.Examples.Loops.PlanarLoops_analytic.h:968:36: error: redeclaration of ‘StatArrayDim1<double, 3, true> PlanarLoops_analytic::_jointRRR1_P_jointUSR_P_revolute_P_e_’
  968 |     StatArrayDim1<double, 3, true> _jointRRR1_P_jointUSR_P_revolute_P_e_;
      |                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
OMCppModelica.Mechanics.MultiBody.Examples.Loops.PlanarLoops_analytic.h:418:36: note: previous declaration ‘StatArrayDim1<double, 3, true> PlanarLoops_analytic::_jointRRR1_P_jointUSR_P_revolute_P_e_’
  418 |     StatArrayDim1<double, 3, true> _jointRRR1_P_jointUSR_P_revolute_P_e_;
      |                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
```
@kabdelhak can you please have a look?

**Comment by rfranke** [comment]
The duplicate declaration as algebraic variable disappears for `Buildings.HeatTransfer.Windows.BaseClasses.Examples.TransmittedRadiation` after #10713. SimCode reads now:
```
...
paramVars
----------------------
...
index:168: winTra.radDat.absExtIrrExtSha (no alias)  initial: 	no arrCref index:(280) [2,11,1]
...
```

**Comment by bilderbuchi** [comment]
> the complete MSL compiles now.

Nice achievement!
Out of curiosity, how do/could you keep it that way? I assume that the whole testsuite is much too expensive to run as a check for every PR (i.e. before merging, to avoid merging regressions in the first place).
Do you get automated emails (with a changeset information or somesuch) if there is a (serious) regression? Or do you have to notice regressions accidentally and then manually bisect backwards?

**Comment by rfranke** [comment]
Yes, we get regular e-mails from the server. Not meaning that this is perfect -- this issue should never have happened for instance as the fix of one problem broke the `PlanarLoops_analytic` example of MSL.
Generally we attempt to cover as many features as possible with small examples in the commit tests that must pass for each pull request.

**Comment by casella** [comment]
> Nice achievement! 😄 Out of curiosity, how do/could you keep it that way? I assume that the whole testsuite is much too expensive to run as a check for every PR (i.e. before merging, to avoid merging regressions in the first place).

Indeed. You can check the regression reports from https://libraries.openmodelica.org/branches/history/, just get in the directory you are interested. We run the library testsuite daily with master (i.e. default), cpp and fmi configurations. Other configurations are run on demand. newInst is no longer run since we made it the default.

We also run all the libraries with older released versions every now and then, so we can get a nice overview of how the support level improved over time, see https://libraries.openmodelica.org/branches/overview.html. I just added reporting for version 1.21, it should pop up in a couple of days at most, unless I broke something in the scripts 😅

**Comment by rfranke** [comment]
@casella the tests appear to have a problem this week. Fmi ran the last time on 2023-05-20 09:23:02, Cpp on 2023-05-21 18:54:50. C a bit better, 2023-05-24 04:57:40, but still too long for a run every 12 hours.
Can this be related to your 1.21 change?

**Comment by casella** [comment]
I ran some heavy tests for Karim

- https://libraries.openmodelica.org/branches/heavy_tests/LargeTestSuite_NB/LargeTestSuite_NB.html
- https://libraries.openmodelica.org/branches/heavy_tests/LargeTestSuite_OB/LargeTestSuite_OB.html

which seized an entire Ryzen server for 6 and 19 hours, respectively. I guess that clogged up the pipeline a bit, I hope this is now resolved.
