### ISSUE TITLE
OMCFactory.cpp:85:16: error: ‘io_service’ in namespace ‘boost::asio’ does not name a type

### ISSUE THREAD

**Issue by jschueller** [OpenModelica/OpenModelica#13440]
### Description

fails to build with boost 1.87:
```
/usr/local/src/OpenModelica/OMCompiler/SimulationRuntime/cpp/SimCoreFactory/OMCFactory/OMCFactory.cpp:85:16: error: ‘io_service’ in namespace ‘boost::asio’ does not name a type; did you mean ‘has_service’?
   85 |   boost::asio::io_service _ios;
      |                ^~~~~~~~~~
      |                has_service
/usr/local/src/OpenModelica/OMCompiler/SimulationRuntime/cpp/SimCoreFactory/OMCFactory/OMCFactory.cpp: In constructor ‘LoggerXMLTCP::LoggerXMLTCP(std::string, int, LogSettings&)’:
/usr/local/src/OpenModelica/OMCompiler/SimulationRuntime/cpp/SimCoreFactory/OMCFactory/OMCFactory.cpp:43:43: error: ‘from_string’ is not a member of ‘boost::asio::ip::address’
```

### Steps to Reproduce

upgrade to boost 1.87

### Expected Behavior

build succeeds

### Screenshots

na

### Version and OS

 - OpenModelica Version: 1.24.2
 - OS: linux

### Additional Context

na

**Comment by perost** [comment]
I tried fixing the issues with #13441. I'm still on boost 1.86 though (Arch Linux), so let me know if this fixes it for you or if there are more issues that need to be fixed.

**Comment by jschueller** [comment]
I think it passes now, thanks
