### PR TITLE
OMEdit: Fix build with qt 6.10

### PR DESCRIPTION
**Pull request by jschueller**
else I get:
```
openmodelica/OMEdit/OMEditLIB/Modeling/ModelWidgetContainer.cpp:3946:63: error: no matching function for call to 'QString::arg(const RealAnnotation&)'
 3946 |     coOrdinateSystemList.append(QString("initialScale=%1").arg(mCoordinateSystem.getInitialScale()));
```

### CODE REVIEW

File: OMEdit/OMEditLIB/Modeling/ModelWidgetContainer.cpp [hunk 1]
```diff
@@ -3931,7 +3931,7 @@ void GraphicsView::getCoordinateSystemAndGraphics(QStringList &coOrdinateSystemL
   }
   // add the initial scale
   if (mCoordinateSystem.hasInitialScale()) {
-    coOrdinateSystemList.append(QString("initialScale=%1").arg(mCoordinateSystem.getInitialScale()));
+    coOrdinateSystemList.append(QString("initialScale=%1").arg(static_cast<qreal>(mCoordinateSystem.getInitialScale())));
```
Comment (adeas31) [inline OMEdit/OMEditLIB/Modeling/ModelWidgetContainer.cpp]: I guess proper fix is to use `toQString()` i.e.,

`coOrdinateSystemList.append(QString("initialScale=%1").arg(static_cast<qreal>(mCoordinateSystem.getInitialScale().toQString())));`

**Review by adeas31 — CHANGES_REQUESTED** [review]

**Comment by adeas31** [comment]
@perost I know you are using qt6. Can you please compile and see if it works?

**Comment by perost** [comment]
> @perost I know you are using qt6. Can you please compile and see if it works?

Works fine for me with qt 6.10 both with or without the fix.

File: OMEdit/OMEditLIB/Modeling/ModelWidgetContainer.cpp (hunk 1 above)
Comment (jschueller) [reply OMEdit/OMEditLIB/Modeling/ModelWidgetContainer.cpp]: done

Comment (perost) [reply OMEdit/OMEditLIB/Modeling/ModelWidgetContainer.cpp]: I don't think that's correct, `getInitialScale` returns a `RealAnnotation` which has a conversion operator for `qreal`. Converting it to a QString and then back to `qreal` is unnecessary, and I don't think you can cast a `QString` to `qreal` like that anyway.

Comment (perost) [reply OMEdit/OMEditLIB/Modeling/ModelWidgetContainer.cpp]: Seems I was too slow, converting it to a `QString` like with the last change is of course also fine.

**Comment by adeas31** [comment]
> > @perost I know you are using qt6. Can you please compile and see if it works?
> 
> Works fine for me with qt 6.10 both with or without the fix.

OK but I still think we should use `toQString` instead of doing implicit/explicit cast.

**Comment by jschueller** [comment]
> > @perost I know you are using qt6. Can you please compile and see if it works?
> 
> Works fine for me with qt 6.10 both with or without the fix.

@perost maybe the error is maybe not linked to qt 6.10 but nevertheless I get this error:
```
769.0 /tmp/OpenModelica/OMEdit/OMEditLIB/Modeling/ModelWidgetContainer.cpp: In member function ‘void GraphicsView::getCoordinateSystemAndGraphics(QStringList&, QStringList&)’:
769.0 /tmp/OpenModelica/OMEdit/OMEditLIB/Modeling/ModelWidgetContainer.cpp:3934:63: error: no matching function for call to ‘QString::arg(const RealAnnotation&)’
769.0  3934 |     coOrdinateSystemList.append(QString("initialScale=%1").arg(mCoordinateSystem.getInitialScale()));
769.0       |                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
769.0 /tmp/OpenModelica/OMEdit/OMEditLIB/Modeling/ModelWidgetContainer.cpp:3934:63: note: there are 4 candidates
769.0 In file included from /usr/include/qt6/QtCore/qobject.h:11,
769.0                  from /usr/include/qt6/QtCore/QObject:1,
769.0                  from /tmp/OpenModelica/OMEdit/OMEditLIB/Util/StringHandler.h:38,
769.0                  from /tmp/OpenModelica/OMEdit/OMEditLIB/Annotations/ShapeAnnotation.h:38,
769.0                  from /tmp/OpenModelica/OMEdit/OMEditLIB/Element/Element.h:38,
769.0                  from /tmp/OpenModelica/OMEdit/OMEditLIB/Modeling/ModelWidgetContainer.h:38,
769.0                  from /tmp/OpenModelica/OMEdit/OMEditLIB/Modeling/ModelWidgetContainer.cpp:35:
769.0 /usr/include/qt6/QtCore/qstring.h:324:27: note: candidate 1: ‘template<class T, typename std::enable_if<conjunction_v<std::disjunction<std::is_integral<_Tp>, std::conjunction<std::is_enum<_Tp>, std::negation<q23::is_scoped_enum<E, is_enum_v<E> > > > >, std::negation<std::disjunction<std::is_same<typename std::remove_cv<typename std::remove_reference<_Tp>::type>::type, _Float16>, std::is_same<typename std::remove_cv<typename std::remove_reference<_Tp>::type>::type, qfloat16>, std::is_floating_point<_Tp> > >, std::negation<std::conjunction<std::negation<QtPrivate::treat_as_integral_arg<typename std::remove_cv< <template-parameter-1-1> >::type> >, std::is_convertible<T, QAnyStringView> > > >, bool>::type <anonymous> > QString QString::arg(T, int, int, QChar) const’
769.0   324 |     [[nodiscard]] QString arg(T a, int fieldWidth = 0, int base = 10,
769.0       |                           ^~~
769.0 /usr/include/qt6/QtCore/qstring.h:324:27: note: template argument deduction/substitution failed:
769.0 /usr/include/qt6/QtCore/qstring.h:323:53: error: no type named ‘type’ in ‘struct std::enable_if<false, bool>’
769.0   323 |     template <typename T, if_integral_non_char<T> = true>
769.0       |                                                     ^~~~
769.0 /usr/include/qt6/QtCore/qstring.h:339:27: note: candidate 2: ‘template<class T, typename std::enable_if<std::disjunction<std::is_same<typename std::remove_cv<typename std::remove_reference<_Tp>::type>::type, _Float16>, std::is_same<typename std::remove_cv<typename std::remove_reference<_Tp>::type>::type, qfloat16>, std::is_floating_point<_Tp> >::value, bool>::type <anonymous> > QString QString::arg(T, int, char, int, QChar) const’
769.0   339 |     [[nodiscard]] QString arg(T a, int fieldWidth = 0, char format = 'g', int precision = -1,
769.0       |                           ^~~
769.0 /usr/include/qt6/QtCore/qstring.h:339:27: note: template argument deduction/substitution failed:
769.0 /usr/include/qt6/QtCore/qstring.h:338:50: error: no type named ‘type’ in ‘struct std::enable_if<false, bool>’
769.0   338 |     template <typename T, if_floating_point<T> = true>
769.0       |                                                  ^~~~
769.0 /usr/include/qt6/QtCore/qstring.h:344:27: note: candidate 3: ‘template<class T, typename std::enable_if<std::conjunction<std::negation<QtPrivate::treat_as_integral_arg<typename std::remove_cv< <template-parameter-1-1> >::type> >, std::is_convertible<T, QAnyStringView> >::value, bool>::type <anonymous> > QString QString::arg(const T&, int, QChar) const’
769.0   344 |     [[nodiscard]] QString arg(const T &a, int fieldWidth = 0, QChar fillChar = u' ') const
769.0       |                           ^~~
769.0 /usr/include/qt6/QtCore/qstring.h:344:27: note: template argument deduction/substitution failed:
769.0 /usr/include/qt6/QtCore/qstring.h:343:47: error: no type named ‘type’ in ‘struct std::enable_if<false, bool>’
769.0   343 |     template <typename T, if_string_like<T> = true>
769.0       |                                               ^~~~
769.0 /usr/include/qt6/QtCore/qstring.h:364:5: note: candidate 4: ‘template<class ... Args> typename std::enable_if<((sizeof... (Args) >= 2) && conjunction_v<std::conjunction<std::negation<QtPrivate::treat_as_integral_arg<typename std::remove_cv<Args>::type> >, std::is_convertible<Args, QAnyStringView> >...>), QString>::type QString::arg(Args&& ...) const’
769.0   364 |     arg(Args &&...args) const
769.0       |     ^~~
769.0 /usr/include/qt6/QtCore/qstring.h:364:5: note: template argument deduction/substitution failed:
769.0 /usr/include/qt6/QtCore/qstring.h: In substitution of ‘template<class ... Args> typename std::enable_if<((sizeof... (Args) >= 2) && conjunction_v<std::conjunction<std::negation<QtPrivate::treat_as_integral_arg<typename std::remove_cv<Args>::type> >, std::is_convertible<Args, QAnyStringView> >...>), QString>::type QString::arg(Args&& ...) const [with Args = {const RealAnnotation&}]’:
769.0 /tmp/OpenModelica/OMEdit/OMEditLIB/Modeling/ModelWidgetContainer.cpp:3934:63:   required from here
769.0  3934 |     coOrdinateSystemList.append(QString("initialScale=%1").arg(mCoordinateSystem.getInitialScale()));
769.0       |                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
769.0 /usr/include/qt6/QtCore/qstring.h:364:5: error: no type named ‘type’ in ‘struct std::enable_if<false, QString>’
769.0   364 |     arg(Args &&...args) const
769.0       |     ^~~
770.8 [ 98%] Building CXX object OMNotebook/OMNotebook/OMNotebookGUI/CMakeFiles/OMNotebook.dir/latexcell.cpp.o
771.8 [ 98%] Building CXX object OMEdit/OMEditLIB/CMakeFiles/OMEditLib.dir/Modeling/QuickInsertWidget.cpp.o
772.6 make[2]: *** [OMEdit/OMEditLIB/CMakeFiles/OMEditLib.dir/build.make:535: OMEdit/OMEditLIB/CMakeFiles/OMEditLib.dir/Modeling/ModelWidgetContainer.cpp.o] Error 1
772.6 make[2]: *** Waiting for unfinished jobs....
772.7 [ 98%] Building CXX object OMNotebook/OMNotebook/OMNotebookGUI/CMakeFiles/OMNotebook.dir/indent.cpp.o
773.3 [ 98%] Building CXX object OMNotebook/OMNotebook/OMNotebookGUI/CMakeFiles/OMNotebook.dir/OMNotebook_autogen/EWIEGA46WW/qrc_res_qt.cpp.o
778.7 /tmp/OpenModelica/OMEdit/OMEditLIB/Modeling/QuickInsertWidget.cpp: In member function ‘void ClassNameFilterProxyModel::setFilterString(const QString&)’:
778.7 /tmp/OpenModelica/OMEdit/OMEditLIB/Modeling/QuickInsertWidget.cpp:285:19: warning: ‘void QSortFilterProxyModel::invalidateFilter()’ is deprecated: Use begin/endFilterChange() instead [-Wdeprecated-declarations]
778.7   285 |   invalidateFilter(); // Retriggers filtering and sorting
778.7       |   ~~~~~~~~~~~~~~~~^~
778.7 In file included from /usr/include/qt6/QtCore/QSortFilterProxyModel:1,
778.7                  from /tmp/OpenModelica/OMEdit/OMEditLIB/Modeling/QuickInsertWidget.h:58,
778.7                  from /tmp/OpenModelica/OMEdit/OMEditLIB/Modeling/QuickInsertWidget.cpp:35:
778.7 /usr/include/qt6/QtCore/qsortfilterproxymodel.h:128:10: note: declared here
778.7   128 |     void invalidateFilter();
```

**Comment by adeas31** [comment]
> > > @perost I know you are using qt6. Can you please compile and see if it works?
> > 
> > 
> > Works fine for me with qt 6.10 both with or without the fix.
> 
> @perost maybe the error is maybe not linked to qt 6.10 but nevertheless I get this error:
> 
> ```
> 769.0 /tmp/OpenModelica/OMEdit/OMEditLIB/Modeling/ModelWidgetContainer.cpp: In member function ‘void GraphicsView::getCoordinateSystemAndGraphics(QStringList&, QStringList&)’:
> 769.0 /tmp/OpenModelica/OMEdit/OMEditLIB/Modeling/ModelWidgetContainer.cpp:3934:63: error: no matching function for call to ‘QString::arg(const RealAnnotation&)’
> 769.0  3934 |     coOrdinateSystemList.append(QString("initialScale=%1").arg(mCoordinateSystem.getInitialScale()));
> 769.0       |                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 769.0 /tmp/OpenModelica/OMEdit/OMEditLIB/Modeling/ModelWidgetContainer.cpp:3934:63: note: there are 4 candidates
> 769.0 In file included from /usr/include/qt6/QtCore/qobject.h:11,
> 769.0                  from /usr/include/qt6/QtCore/QObject:1,
> 769.0                  from /tmp/OpenModelica/OMEdit/OMEditLIB/Util/StringHandler.h:38,
> 769.0                  from /tmp/OpenModelica/OMEdit/OMEditLIB/Annotations/ShapeAnnotation.h:38,
> 769.0                  from /tmp/OpenModelica/OMEdit/OMEditLIB/Element/Element.h:38,
> 769.0                  from /tmp/OpenModelica/OMEdit/OMEditLIB/Modeling/ModelWidgetContainer.h:38,
> 769.0                  from /tmp/OpenModelica/OMEdit/OMEditLIB/Modeling/ModelWidgetContainer.cpp:35:
> 769.0 /usr/include/qt6/QtCore/qstring.h:324:27: note: candidate 1: ‘template<class T, typename std::enable_if<conjunction_v<std::disjunction<std::is_integral<_Tp>, std::conjunction<std::is_enum<_Tp>, std::negation<q23::is_scoped_enum<E, is_enum_v<E> > > > >, std::negation<std::disjunction<std::is_same<typename std::remove_cv<typename std::remove_reference<_Tp>::type>::type, _Float16>, std::is_same<typename std::remove_cv<typename std::remove_reference<_Tp>::type>::type, qfloat16>, std::is_floating_point<_Tp> > >, std::negation<std::conjunction<std::negation<QtPrivate::treat_as_integral_arg<typename std::remove_cv< <template-parameter-1-1> >::type> >, std::is_convertible<T, QAnyStringView> > > >, bool>::type <anonymous> > QString QString::arg(T, int, int, QChar) const’
> 769.0   324 |     [[nodiscard]] QString arg(T a, int fieldWidth = 0, int base = 10,
> 769.0       |                           ^~~
> 769.0 /usr/include/qt6/QtCore/qstring.h:324:27: note: template argument deduction/substitution failed:
> 769.0 /usr/include/qt6/QtCore/qstring.h:323:53: error: no type named ‘type’ in ‘struct std::enable_if<false, bool>’
> 769.0   323 |     template <typename T, if_integral_non_char<T> = true>
> 769.0       |                                                     ^~~~
> 769.0 /usr/include/qt6/QtCore/qstring.h:339:27: note: candidate 2: ‘template<class T, typename std::enable_if<std::disjunction<std::is_same<typename std::remove_cv<typename std::remove_reference<_Tp>::type>::type, _Float16>, std::is_same<typename std::remove_cv<typename std::remove_reference<_Tp>::type>::type, qfloat16>, std::is_floating_point<_Tp> >::value, bool>::type <anonymous> > QString QString::arg(T, int, char, int, QChar) const’
> 769.0   339 |     [[nodiscard]] QString arg(T a, int fieldWidth = 0, char format = 'g', int precision = -1,
> 769.0       |                           ^~~
> 769.0 /usr/include/qt6/QtCore/qstring.h:339:27: note: template argument deduction/substitution failed:
> 769.0 /usr/include/qt6/QtCore/qstring.h:338:50: error: no type named ‘type’ in ‘struct std::enable_if<false, bool>’
> 769.0   338 |     template <typename T, if_floating_point<T> = true>
> 769.0       |                                                  ^~~~
> 769.0 /usr/include/qt6/QtCore/qstring.h:344:27: note: candidate 3: ‘template<class T, typename std::enable_if<std::conjunction<std::negation<QtPrivate::treat_as_integral_arg<typename std::remove_cv< <template-parameter-1-1> >::type> >, std::is_convertible<T, QAnyStringView> >::value, bool>::type <anonymous> > QString QString::arg(const T&, int, QChar) const’
> 769.0   344 |     [[nodiscard]] QString arg(const T &a, int fieldWidth = 0, QChar fillChar = u' ') const
> 769.0       |                           ^~~
> 769.0 /usr/include/qt6/QtCore/qstring.h:344:27: note: template argument deduction/substitution failed:
> 769.0 /usr/include/qt6/QtCore/qstring.h:343:47: error: no type named ‘type’ in ‘struct std::enable_if<false, bool>’
> 769.0   343 |     template <typename T, if_string_like<T> = true>
> 769.0       |                                               ^~~~
> 769.0 /usr/include/qt6/QtCore/qstring.h:364:5: note: candidate 4: ‘template<class ... Args> typename std::enable_if<((sizeof... (Args) >= 2) && conjunction_v<std::conjunction<std::negation<QtPrivate::treat_as_integral_arg<typename std::remove_cv<Args>::type> >, std::is_convertible<Args, QAnyStringView> >...>), QString>::type QString::arg(Args&& ...) const’
> 769.0   364 |     arg(Args &&...args) const
> 769.0       |     ^~~
> 769.0 /usr/include/qt6/QtCore/qstring.h:364:5: note: template argument deduction/substitution failed:
> 769.0 /usr/include/qt6/QtCore/qstring.h: In substitution of ‘template<class ... Args> typename std::enable_if<((sizeof... (Args) >= 2) && conjunction_v<std::conjunction<std::negation<QtPrivate::treat_as_integral_arg<typename std::remove_cv<Args>::type> >, std::is_convertible<Args, QAnyStringView> >...>), QString>::type QString::arg(Args&& ...) const [with Args = {const RealAnnotation&}]’:
> 769.0 /tmp/OpenModelica/OMEdit/OMEditLIB/Modeling/ModelWidgetContainer.cpp:3934:63:   required from here
> 769.0  3934 |     coOrdinateSystemList.append(QString("initialScale=%1").arg(mCoordinateSystem.getInitialScale()));
> 769.0       |                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 769.0 /usr/include/qt6/QtCore/qstring.h:364:5: error: no type named ‘type’ in ‘struct std::enable_if<false, QString>’
> 769.0   364 |     arg(Args &&...args) const
> 769.0       |     ^~~
> 770.8 [ 98%] Building CXX object OMNotebook/OMNotebook/OMNotebookGUI/CMakeFiles/OMNotebook.dir/latexcell.cpp.o
> 771.8 [ 98%] Building CXX object OMEdit/OMEditLIB/CMakeFiles/OMEditLib.dir/Modeling/QuickInsertWidget.cpp.o
> 772.6 make[2]: *** [OMEdit/OMEditLIB/CMakeFiles/OMEditLib.dir/build.make:535: OMEdit/OMEditLIB/CMakeFiles/OMEditLib.dir/Modeling/ModelWidgetContainer.cpp.o] Error 1
> 772.6 make[2]: *** Waiting for unfinished jobs....
> 772.7 [ 98%] Building CXX object OMNotebook/OMNotebook/OMNotebookGUI/CMakeFiles/OMNotebook.dir/indent.cpp.o
> 773.3 [ 98%] Building CXX object OMNotebook/OMNotebook/OMNotebookGUI/CMakeFiles/OMNotebook.dir/OMNotebook_autogen/EWIEGA46WW/qrc_res_qt.cpp.o
> 778.7 /tmp/OpenModelica/OMEdit/OMEditLIB/Modeling/QuickInsertWidget.cpp: In member function ‘void ClassNameFilterProxyModel::setFilterString(const QString&)’:
> 778.7 /tmp/OpenModelica/OMEdit/OMEditLIB/Modeling/QuickInsertWidget.cpp:285:19: warning: ‘void QSortFilterProxyModel::invalidateFilter()’ is deprecated: Use begin/endFilterChange() instead [-Wdeprecated-declarations]
> 778.7   285 |   invalidateFilter(); // Retriggers filtering and sorting
> 778.7       |   ~~~~~~~~~~~~~~~~^~
> 778.7 In file included from /usr/include/qt6/QtCore/QSortFilterProxyModel:1,
> 778.7                  from /tmp/OpenModelica/OMEdit/OMEditLIB/Modeling/QuickInsertWidget.h:58,
> 778.7                  from /tmp/OpenModelica/OMEdit/OMEditLIB/Modeling/QuickInsertWidget.cpp:35:
> 778.7 /usr/include/qt6/QtCore/qsortfilterproxymodel.h:128:10: note: declared here
> 778.7   128 |     void invalidateFilter();
> ```

@jschueller does `toQString()` works?

**Comment by jschueller** [comment]
yes, I updated my patch
