### PR TITLE
CMake configuration support for OMCompiler

### PR DESCRIPTION
**Pull request by mahge**
This is an attempt to have a CMake configuration support for OMC. Right now the focus is in getting OMCompiler working. 
This is **not ready at all**. It is here just for early discussion. If it is deemed unnecessary it might be removed completely. 

The idea is to aim for recent versions of cmake. (a.k.a "modern" CMake). This means it is intended to work only with **CMake > 3.14**. It should be easy to get this (or later) versions of CMake on most platforms. On _MinGW_ you can use the **Windows** version of CMake which is, right now, at 3.17.2 (stable) 

# How to build
It is pretty straightforward cmake stuff.
It does not give you an _omc executable_ at the moment. But if you want to try it out anyway 

```sh
cd OMCompiler
mkdir build_cmake && cd build_cmake

# Wno-dev to hide some cmake warnings from 3rdParty
cmake .. -Wno-dev -G <your_generator> # e.g. -G "MSYS Makefiles" for OMDev MSYS

make -j -Oline # -Oline for GNU Makefiles so that your colors do not get messed up.
# cmake --build ./ --config Release --parallel 5 # If you want to be generic. 
```

# Benefits
- It forces us to have proper structure. 
- Same build configuration on different platforms.
- _Modern_ CMake: automatic configuration propagation.
  - Cleanly specify for each library:
    - Where is is coming from?
    - Which libraries does it depend on?
    - Where do those libraries come from.
    - What header files does it need?
    - What header files should its dependents use?
    - What compilation flags and options does it need?
    - What compilation flags and options its dependents should use?
    - ...  
- _Potentially_ use different build systems.
  - Ninja
  - MSBuild (one day, in the distant future)
- Clean out of source builds.
- ...

# Potential (Further improvement)
- Use CMake aware package manager, e.g., vcpkg, connan ...
- Use CMake's fetch_content (configure time downloading) to get anything that is not available through package manager or anything that needs patching and custom handling.
 
# Progress

- [x] OMCompiler/3rdParty/(most)
- [x] OMCompiler/Parser
- [x] OMCompiler/Compiler/runtime
- [x] OMCompiler/Compiler/Template
- [x] OMCompiler/SimulationRuntime/c/{OpenModelicaRuntime, OpenModelicaFMIRuntime}
  - More can be added as needed.

- [ ] Figure out a way to cleanly handle the `MetaModelica` source files to build `libOpenModelica`.
  - This is the big one. To simplify things, the idea is to aim for no bootstrapping support yet. Just compilation using installed OMC.
- [ ] Add a header only interface library for all the common include files. e.g. `openmodelica.h`, `revision.h`
- [ ] Handle all libraries in OMCompiler/SimulationRuntime/c. Some are left for later.
- [ ] No free standing "outside" include directories. All includes should come from dependency targets.

- [ ] ... (Many more if this goes on)

### CODE REVIEW

**Comment by adrpo** [comment]
As far as I know we need to support systems that only have cmake 2.8.
While is nice to have as you can generate makefiles for different systems, cmake has its issues, sometimes is really hard to achieve the things you want from it in an easy way. Good luck!

**Comment by mahge** [comment]
@adrpo Ya I noticed some changes you made to get things working for systems that have older versions of cmake. I am guessing these are long term support systems like redhat that come with too old cmake versions and these are systems that we build distributions on. It should be possible to compile CMake from source for these systems if we need to. If not we can still use autoconf on them as we do now. We only need to make sure that anything that does not have autoconf compilation (e.g. 3rdParty libraries that only have CMake config) are able to compile with CMake 2.8. CMake is extremely backward compatible so these will work with newer versions of CMake with no problem. 

As it is now I have tried to keep the modification to 3rdParty libraries' configurations to a minimum. The changes to them are mostly making sure that variables do not conflict between them (e.g. `BUILD_SHARED_LIBS` -> `SUNDIALS_BUILD_SHARED_LIBS`)

The reasoning behind going with 3.14 is to have something cleaner. If we go with older cmake versions we will be back at the same overly complicated and difficult to understand cmake files as we had. 

The automatic handling of configuration propagation is what we need. For example if you compile Sundials IDA static library (sundials_ida_static.a) and you attach a definition `SUNDIALS_LINK_STATIC` to it as

`target_compile_definitions(sundials_ida_static INTERFACE SUNDIALS_LINK_STATIC) `

You can be sure that every library that later links to sundials will have all its sources compiled with `-DSUNDIALS_LINK_STATIC`. 

Another example would be GC. If you enable threads, you want to have sources for GC itself and everything that links to GC to compile with -DGC_THREADS. If you do not, then there will be no compilation error but threads might not be created through GC_ functions for some of your libraries. 

`target_compile_definitions(gc-lib PUBLIC GC_THREADS)`

will make sure that sources get compiled with proper defines.
The plan is for the future. We gotta keep up :).



I know CMake has had its issues. It is by no means the perfect thing for this job. But it is also not worse than autotools and manual makefiles. Especially the new cmake style of specifying dependencies. For better or worse it is becoming the default build system for C/C++ and it does not hurt to have it. We already have the CMakefiles in place anyway.

**Review by lochel — APPROVED** [review]
LGTM; I guess proper testing must be done on the go

**Comment by AnHeuermann** [comment]
I wasn't even fast enough to build it before it was merged.
I need to build CMake on my own to be able to even try to compile (Ubuntu 18.04 has no CMake that is new enough).

The first error I get:
```bash
$  cmake .. -Wno-dev -G "Unix Makefiles"
CMake Error at 3rdParty/lpsolve/CMakeLists.txt:5 (find_package):
  By not providing "Findbison.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "bison", but
  CMake did not find one.

  Could not find a package configuration file provided by "bison" with any of
  the following names:

    bisonConfig.cmake
    bison-config.cmake

  Add the installation prefix of "bison" to CMAKE_PREFIX_PATH or set
  "bison_DIR" to a directory containing one of the above files.  If "bison"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/home/aheuermann1/workspace/OpenModelica/OMCompiler/build_cmake/CMakeFiles/CMakeOutput.log".
See also "/home/aheuermann1/workspace/OpenModelica/OMCompiler/build_cmake/CMakeFiles/CMakeError.log".
```
@mahge What am I missing here? I'm using 3rd-Party at b3645c.

File: OMCompiler/SimulationRuntime/c/CMakeLists.txt [hunk 1]
```diff
@@ -1,509 +1,44 @@
...
-  SET(SUNDIALS_LIBRARIES ${SUNDIALS_LIBRARY_CVODE} ${SUNDIALS_LIBRARY_IDA} ${SUNDIALS_LIBRARY_NVEC} ${SUNDIALS_KINSOL})
-
-ENDIF(SUNDIALS_INCLUDE_DIR AND
-      SUNDIALS_LIBRARY_CVODE AND
-      SUNDIALS_LIBRARY_IDA AND
-   SUNDIALS_LIBRARY_NVEC AND
-   SUNDIALS_KINSOL)
-
-  # includes
-  INCLUDE_DIRECTORIES(${OMCTRUNCHOME}/OMCompiler/SimulationRuntime/c)
```
Comment (AnHeuermann) [inline OMCompiler/SimulationRuntime/c/CMakeLists.txt:341]: How are include directories managed now?

**Review by AnHeuermann — COMMENTED** [review]
## CMake Version ##
As @adrpo pointed out not everybody has a version of CMake greater then 3.14 available. Building it from scratch is (at least on my machine) really straight forward, but we should add some word to the READMEs.

## More documentation ##
I would need some sort of documentation for us developers how to add stuff to the compiler.
E.g. if I would generate a new MetaModelica file `crazyNewStuff.mo` where I would need to add it so that it get's compiled?
Until now this was always a mystery to me and I basically searched for the nearest file that was already in the Compiler and look where it is added and add it there as well. If it was not working just add or delete something at random until it works...
Also what MetaModelica belongs to which stage of the omc was never clear to me.

The same is true for C files in the simulation runtime. It was more clear, but as we have Makefiles + CMake and both with differences for mingw, msvc and Unix. Luckily this is going to change, but a small how-to would be great.

## Unused folder ##
There are some files in `OMCompiler/Compiler/.cmake/unused/`. Do they have any meaning?

## Overall ## 
But to be honest, I'm not good with CMake and can't really review much of this PR. And it is a huge PR.

File: OMCompiler/CMakeLists.txt [hunk 2]
```diff
@@ -1,47 +1,23 @@
-# Jens Frenkel, Jens.Frenkel@tu-dresden.de, 2010-03-30
-# CMakefile for compilation of OMC
+cmake_minimum_required(VERSION 3.14)
```
[the remark this answers is not in the document]
Comment (sjoelund) [reply OMCompiler/CMakeLists.txt:1]: It's a big problem for nightly builds and Jenkins, and especially source packages

[the remark this answers is not in the document]
Comment (mahge) [reply OMCompiler/CMakeLists.txt:1]: @AnHeuermann About CMake 3.14, I understand absolutely what you mean. It will be a hassle to get recent CMake versions on long term releases of some Linux distros. The decision I had to make was whether to use old cmake and repeat the same "quirks" of CMake that everyone hated to begin with OR just go for the new and improved cmake and have something that can be somehow future proof.  

This definitely needs some READMEs and proper documentation. I will do that soon. It is not over yet at all. The MetaModelica compilation still needs some work. There are issues with some 3rdParty libs and many other problems. I t was just that I have other things to fix right now. It is also on a relatively stable stage now which means you can for example start adding your won libraries to this. I will try to add some documentation about that. However, the good thing about these recent version of cmake is that it should be very straight forward to add new libraries. Take a look at some of the libraries in simulation runtime. It will make sense quickly. I will add this on the documentation as well.

There is still a lot left to do.

[the remark this answers is not in the document]
Comment (mahge) [reply OMCompiler/CMakeLists.txt:1]: @sjoelund You do not have to use it on Jenkins if it is a big problem.

File: OMCompiler/SimulationRuntime/c/CMakeLists.txt (hunk 1 above)
Comment (mahge) [reply OMCompiler/SimulationRuntime/c/CMakeLists.txt:341]: This is a good example actually. You now specify include directories separately for each target. 

In this specific case the C source files all use includes relative to their location. So there was no need for an explicit include directory. 

However, libraries that link to these libraries need to know where to find the headers (right?). For those cases, we have this (line 30).

`target_include_directories(OpenModelicaRuntimeC INTERFACE ${CMAKE_CURRENT_SOURCE_DIR})`

This (the `INTERFACE `part) tells every library that links to `OpenModelicaRuntimeC `to add `${CMAKE_CURRENT_SOURCE_DIR}` (which is `SimulationRuntime/c`) to its include directory list, i.e. they will be compiled with `-I  ...SimulationRuntime/c`.

See _OMCompiler/Parser/CMakeLists.txt_ for example. You can see (line 40) that the library _omparse_ is linked to _OpenModelicaRuntimeC_. There is no need to explicitly specify `INCLUDE_DIRECTORIES(${OMCTRUNCHOME}/OMCompiler/SimulationRuntime/c)` here. It will be done automatically because of the interface specifier above.

File: OMCompiler/CMakeLists.txt (hunk 2 above)
[the remark this answers is not in the document]
Comment (mahge) [reply OMCompiler/CMakeLists.txt:1]: @AnHeuermann 
> There are some files in OMCompiler/Compiler/.cmake/unused/. Do they have any meaning?
That was an attempt to add MetaModelica as a kind of "native" language to CMake. It did not work out as good as expected for many reasons. I had it in my branch and was not removed. I will remove it.

[the remark this answers is not in the document]
Comment (mahge) [reply OMCompiler/CMakeLists.txt:1]: @AnHeuermann 
> E.g. if I would generate a new MetaModelica file crazyNewStuff.mo where I would need to add it so that it get's compiled?

Hopefully you only have to add it one place when this is over. That would be at `OMCompiler/Compiler/.cmake/meta_modelica_source_list.cmake`

Right now you need to the package name to `OMCompiler/Compiler/.cmake/package_list.txt` but that won't be necessary later.

**Comment by mahge** [comment]
> 
> 
> I wasn't even fast enough to build it before it was merged.
> I need to build CMake on my own to be able to even try to compile (Ubuntu 18.04 has no CMake that is new enough).
> 
> The first error I get:
> 
> ```shell
> $  cmake .. -Wno-dev -G "Unix Makefiles"
> [...]
> CMake Error at 3rdParty/lpsolve/CMakeLists.txt:5 (find_package):
>   By not providing "Findbison.cmake" in CMAKE_MODULE_PATH this project has
>   asked CMake to find a package configuration file provided by "bison", but
>   CMake did not find one.
> 
>   Could not find a package configuration file provided by "bison" with any of
>   the following names:
> 
>     bisonConfig.cmake
>     bison-config.cmake
> 
>   Add the installation prefix of "bison" to CMAKE_PREFIX_PATH or set
>   "bison_DIR" to a directory containing one of the above files.  If "bison"
>   provides a separate development package or SDK, be sure it has been
>   installed.
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/aheuermann1/workspace/OpenModelica/OMCompiler/build_cmake/CMakeFiles/CMakeOutput.log".
> See also "/home/aheuermann1/workspace/OpenModelica/OMCompiler/build_cmake/CMakeFiles/CMakeError.log".
> ```
> 
> @mahge What am I missing here? I'm using 3rd-Party at b3645c.

I am not sure. CMake should have a FindBISON module since 3.7
https://cmake.org/cmake/help/v3.7/module/FindBISON.html

Can you try with upper case BISON instead?

**Comment by adrpo** [comment]
This broke the windows builds. We should have tested this with labels to build and test for WIndows and Mac.
```
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.14 or higher is required.  You are running version 3.4.0
```

What do we do now?

File: OMCompiler/SimulationRuntime/c/CMakeLists.txt (hunk 1 above)
Comment (adrpo) [reply OMCompiler/SimulationRuntime/c/CMakeLists.txt:341]: @mahge this is good example of needing to be an expert in CMake to understand all the weird implicit stuff and the need to debug for hours to find a missing include.

**Comment by AnHeuermann** [comment]
This will also cause problems for people running `$ git submodules foreach --recursive "git checkout master && git pull` because the master of 3rdParty does not match the master of OpenModelica. And as we noticed the last time I did something along these lines there are people who do this.

I would suggest to revert this commit, reactivate this PR and wait for the 1.16 release.
At least I want to get it to run on my Ubuntu before merging it into the master.

But all in all I'm still in favor of using (only) a modern CMake for our build system.

**Comment by adrpo** [comment]
For 3rdParty we need to do as is explained in:
https://github.com/OpenModelica/OpenModelica/blob/master/CONTRIBUTING.md
at the bottom of the page.

**Comment by adrpo** [comment]
I will revert this for now until we do proper testing on Windows and Mac.

**Comment by adrpo** [comment]
The changes to 3rdParty are on on branch:
https://github.com/OpenModelica/OMCompiler-3rdParty/commits/CMakeBuildSupport
and the master has been reverted to previous position.

**Comment by mahge** [comment]
The commits on 3rdParty got squashed on merge resulting in a new hash. This should have been updated to that new hash. This should have been updated to that hash after 3rdParty was merged.
