### ISSUE TITLE
OMEdit on master branch cannot be built with OMSimulator 3.0

### ISSUE THREAD

**Issue by Dr-Zero** [OpenModelica/OpenModelica#14228]
### Description

It is impossible to build OMEdit with current OMSimulator master branch (v3.0).

### Steps to Reproduce

Attempt to build latest version following the instructions on github after updating submodules with the command:
`git submodule foreach --recursive "git checkout master && git pull"`

This will retrieve OMSimulator with commit  [10a23e5404f937dc8bf3753df01a32dc495e712f](https://github.com/OpenModelica/OMSimulator/commit/10a23e5404f937dc8bf3753df01a32dc495e712f) that "Remove TLM References".

Build of OMEdit will fail, more specifically OMEditLIB with several missing declaration errors, such as:
```
...OpenModelica/OMEdit/OMEditLIB/OMS/OMSProxy.h:70:41: error: ‘oms_tlm_interpolation_t’ has not been declared
   70 |   static QString getInterpolationString(oms_tlm_interpolation_t interpolation);
```
 among others. A quick inspection of this commit can verify that those symbols, once inside `OMSimulator/include/OMSimulator/Types.h`, were indeed removed.

### Workarounds

Current OMEdit on master branch (and everything under OpenModelica repository) can still be built by checking out branch `maintenance/v2.1` under OMSimulator.

**Comment by Dr-Zero** [comment]
I created a pull request (#14232) that removes TLM references from OMEditLIB. That exposes another significant update on OMSimulator caused by commit [61ef2f4d8eeb5e186c57a5dc84e6bb3a23e91d1d](https://github.com/OpenModelica/OMSimulator/commit/61ef2f4d8eeb5e186c57a5dc84e6bb3a23e91d1d), the removal of "absolute tolerance from api". As such, this patch only allows compilation til commit  [b2b897d6242b1de0a947b174537724b8e068df5c](https://github.com/OpenModelica/OMSimulator/commit/b2b897d6242b1de0a947b174537724b8e068df5c). Since this is a totally different issue, I decided to exclude it from this pull request.

**Comment by Dr-Zero** [comment]
I wrote a pull request (#14241) to remove absolute tolerance from OMEdit. This, combined with the previous previous request (thanks for the merge) fully solves this issue.

**Comment by casella** [comment]
@arun3688, @adeas31 can you please follow this up?

**Comment by Dr-Zero** [comment]
Newest versions of OMSimulator API have a function with ```signals``` as a parameter name:

```
OMSAPI oms_status_enu_t OMSCALL oms_getResultFileSignals(const char* filename, const char** signals);
```
from [OMSimulator.h](https://github.com/OpenModelica/OMSimulator/blob/master/include/OMSimulator/OMSimulator.h) (currently at line 107).

This was introduced on  OpenModelica/OMSimulator@157385c28eef5118078db9ef074fd30018eb4c21 ("add support for reading mat files for ComponentTable").

This of course create problems for a Qt6 application such as OMEdit, since ```signals``` is a Qt6 Macro.
Disabling Qt6 keywords isn't a good option, since they are used abundantly in OMEdit, including ```signals```.

I suppose the best approach would be to undefine temporarily the signals macro for OMSimulator inclusion.

**Comment by arun3688** [comment]
@Dr-Zero Yes that is true, OMSimulator 3.0 is currently a work in progress and it is not integrated with OMEdit, You have to switch to `maintenance/v2.1` branch and build OMEdit

**Comment by adrpo** [comment]
@lochel, @arun3688, should we maybe not use `signals` as a variable name in OMSimulator? Maybe just use `signalNames` instead?

**Comment by arun3688** [comment]
@adrpo Ah i see that, sure we can rename to signalNames, i will fix that

**Comment by arun3688** [comment]
@Dr-Zero The issue is fixed with this commit [e544c65201556df4336a1b9ce7cda5e9e4b0e2ba](https://github.com/OpenModelica/OMSimulator/commit/e544c65201556df4336a1b9ce7cda5e9e4b0e2ba), Please pull the latest OMsimulator master and test it

**Comment by Dr-Zero** [comment]
@arun3688 Thank you, that did it.
