### ISSUE TITLE
 Modelica-Buildings Library (master): models fail at C compile because of bogus expressions involving loadResource in the backend

### ISSUE THREAD

**Issue by deepak19015** [OpenModelica/OpenModelica#12481]
**Description**

The solver fails to compile the system and throws compilation error that is Compilation process failed. Exited with code 2.
The following below listed models have same issues:

```
Buildings.DHC.Loads.BaseClasses.Validation.BenchmarkFlowDistribution2
Buildings.DHC.Loads.BaseClasses.Validation.FlowDistributionPumpControl
Buildings.DHC.Networks.Examples.Distribution1PipeExample
Buildings.DHC.Networks.Examples.Distribution2PipeExample
```
On simulating the model in OpenModelica leads to following errors/warnings:
```
1) error: passing 'double' to parameter of incompatible type 'modelica_string' (aka 'void *')
2) 10 errors generated.
3) make: *** [<builtin>: BenchmarkFlowDistribution2_02nls.o] Error 1
4) Compilation process failed. Exited with code 2.
```

**Steps to Reproduce**

Load the Modelica-Buildings master library (Source: https://libraries.openmodelica.org/branches/master/Buildings_latest/Buildings_latest.html)
Simulate the examples model present in Buildings.DHC.Loads.BaseClasses.Validation.BenchmarkFlowDistribution2

**Expected Behavior**

The simulation should compile successfully.

 **Version and OS**

- OpenModelica Version: OpenModelica 1.25.0~dev-112-gb8e50a4
- OS: Ubuntu 20.04 focal
    Versions of used Modelica libraries:
    Modelica 4.0.0
    Buildings 12.0.0

**Comment by casella** [comment]
This actually seems to be a regression introduced in version 1.23.0: `Buildings.DHC.Loads.BaseClasses.Validation.BenchmarkFlowDistribution2` [works in v1.22](https://libraries.openmodelica.org/branches/v1.22/Buildings_latest/files/Buildings_latest_Buildings.DHC.Loads.BaseClasses.Validation.BenchmarkFlowDistribution2.err) but [fails in v1.23](https://libraries.openmodelica.org/branches/v1.23/Buildings_latest/files/Buildings_latest_Buildings.DHC.Loads.BaseClasses.Validation.BenchmarkFlowDistribution2.err)

@deepak19015 can you please run the python script [shown here](https://github.com/OpenModelica/OpenModelica/issues/7917#issuecomment-924895206) and figure out which was the commit that broke that model?

**Comment by deepak19015** [comment]
@casella i have run that python code, no report has been generated. 
![Screenshot from 2024-06-11 15-28-33](https://github.com/OpenModelica/OpenModelica/assets/139556265/867c7bc4-2579-483b-a36c-caff0d0b0123)

**Comment by casella** [comment]
@deepak19015 please try with `--branch=master`

**Comment by deepak19015** [comment]
@casella for branch-master and order- oldest/latest, getting same.no report generated.
![Screenshot from 2024-06-12 12-45-15](https://github.com/OpenModelica/OpenModelica/assets/139556265/0bb6a261-0ee3-45b1-953b-2ea5f6953762)

**Comment by casella** [comment]
Strange. Does it work with the current nightly?

**Comment by deepak19015** [comment]
Today i have checked with windows, all the models are simulated successfully, only one model (`Buildings.DHC.Networks.Examples.Distribution2PipeExample`) taking more time to simulate. But in Ubuntu (nightly build open modelica) all the models are failing while compilation.

**Comment by casella** [comment]
@sjoelund, @adrpo, @AnHeuermann could you please have a quick look? We are supposed to be using clang on both OSs, but I guess there may be some OS-specific macros or ifdefs in the generated code.

**Comment by casella** [comment]
313.15 looks very suspicious. If considered as a temperature in Kelvin, it corresponds to 40 degrees Celsius. Which is a temperature very likely to be found in Buildings models.

**Comment by casella** [comment]
I just tried running Buildings.DHC.Loads.BaseClasses.Validation.BenchmarkFlowDistribution2 with Buildings 1.11.0 and OMC 1.24.0-dev-132-g7055b41 on both Windows and Ubuntu, they both fail in the same way as the [CI](https://libraries.openmodelica.org/branches/master/Buildings_11/files/Buildings_11_Buildings.DHC.Loads.BaseClasses.Validation.BenchmarkFlowDistribution2.err).

**Comment by casella** [comment]
The flat Modelica code contains
```
final parameter Real QHea_flow_nominal(quantity = "Power", unit = "W") = 
  Buildings.DHC.Loads.BaseClasses.getPeakLoad("#Peak space heating load",
   Modelica.Utilities.Files.loadResource(filNam)) / 10.0 "Design heating heat flow rate (>=0)";
parameter Real ter[4].gaiHeaFlo.k = 1.0 / ter[4].QHea_flow_nominal "Gain value multiplied with input signal";
```
By checking with the declarative debugger, the parameter binding equation for `ter[4].gaiHeaFlo.k` is solved by substitution, leading to the wrong C code
```
(data->localData[0]->realVars[557] /* ter[4].con.u_m variable */) = 
  (DIVISION_SIM(10.0,omc_Buildings_DHC_Loads_BaseClasses_getPeakLoad(threadData, MMC_REFSTRINGLIT(tmp0), 
   omc_Modelica_Utilities_Files_loadResource(threadData, 313.15)),
   "Buildings.DHC.Loads.BaseClasses.getPeakLoad(\"#Peak space heating load\", 
    Modelica.Utilities.Files.loadResource(313.15))",equationIndexes)) *
  ((data->localData[0]->realVars[797] /* ter[4].hex.Q2_flow variable */));
```
Clearly there is something going badly wrong in the backend when evaluated QHea_flow_nominal. If I check the declarative debugger for that parameter, I read
```
(assign) QHea_flow_nominal := 0.1 * Buildings.DHC.Loads.BaseClasses.getPeakLoad("#Peak space heating load", 
  Modelica.Utilities.Files.loadResource(313.15))
```
which is where the loadResource(313.15) comes from. Unfortunately no operations are generated, so I don't know what leads the backend to that expression.

The only point in the model where 313.15 shows up is
```
parameter Real T_aHeaWat_nominal(quantity = "ThermodynamicTemperature", unit = "K", displayUnit = "degC", min = 0.0, start = 288.15, nominal = 300.0) = 313.15 "Heating water inlet temperature at nominal conditions";
```
which seems very much unrelated to me. It looks like something very bad is going on at a very low level.

@kabdelhak, @phannebohm can you please try to debug this?

Thanks!

**Comment by casella** [comment]
@kabdelhak, @phannebohm, sorry to bother you with old backend stuff, but this issue is causing 4 simulation failures in Buildings since 1.23.0, we really need to fix that. Thanks!

**Comment by phannebohm** [comment]
Buildings.DHC.Loads.BaseClasses.Validation.BenchmarkFlowDistribution2 simulates successfully on my machine. I get

```
QHea_flow_nominal = 0.1 * Buildings.DHC.Loads.BaseClasses.getPeakLoad("#Peak space heating load",
  Modelica.Utilities.Files.loadResource("modelica://Buildings/Resources/Data/DHC/Loads/Examples/SwissResidential_20190916.mos"))
```

**Comment by casella** [comment]
@phannebohm, I wish I had your version of OMC! 😄 

Seriously, are you sure you are not running these simulation on a branch with some magic fix of your own? 

I'm still getting the very same problems [I see on the CI](https://libraries.openmodelica.org/branches/master/Buildings_11/files/Buildings_11_Buildings.DHC.Loads.BaseClasses.Validation.BenchmarkFlowDistribution2.err) (running Linux) also when running the model on my Windows 11 PC using OMEdit.

**Comment by AndreaBartolini** [comment]
I checked today both the models:
- `Buildings.DHC.Networks.Examples.Distribution1PipeExample` 
- `Buildings.DHC.Networks.Examples.Distribution2PipeExample`

Now they run on the CI and also on my Ubuntu 24.04 under WSL but still fail with the same problem under Win 11 Pro (64-bit).
Under Win 11 I'm using OpenModelica v1.26.0-dev-8-gdac54b2a69 (64-bit).

**Comment by casella** [comment]
@AndreaBartolini dac54b2a69 is quite old, the commit was on Mar 13. Please update the Windows nightly so you get @perost's [magic fix](https://github.com/OpenModelica/OpenModelica/pull/13761).

**Comment by casella** [comment]
I'm closing this ticket for 1.25.0. @AndreaBartolini please reopen if you still see problems with the latest Windows nightly (I don't think so).

**Comment by AndreaBartolini** [comment]
I confirm that under OpenModelica v1.26.0-dev-53-ge574b6c997 (64-bit) they run successfully
