### ISSUE TITLE
Windows build fails linking the ffi DLLs: undefined reference to ModelicaError

### ISSUE THREAD

**Issue by adrpo** [OpenModelica/OpenModelica#16892]
The Windows nightly (`OM_Win_NIGHTLY_BUILD_64bit` #6 and #7) fails to link the ffi DLLs since #16810:

```
ld.exe: ... ModelicaInternal.c:(.text+0x974): undefined reference to `ModelicaFormatError'
ld.exe: ... ModelicaMatIO.c:(.text+0xaf91e): undefined reference to `ModelicaVFormatError'
collect2.exe: error: ld returned 1 exit status
mingw32-make[2]: *** [...build.make:120: OMCompiler/SimulationRuntime/ModelicaExternalC/libModelicaMatIO.dll] Error 1
```

#16810 removed the runtime link from the shared ModelicaExternalC, ModelicaMatIO, ModelicaIO and ModelicaStandardTables libraries on every platform, so the process that loads them provides the ModelicaUtilities symbols. Linux and macOS (with `-undefined,dynamic_lookup`) allow that. A Windows DLL can't leave symbols undefined at link time. Nightly #5, built before #16810, was green.

---
generated by Claude Code
