### ISSUE TITLE
Directional derivative generation fails in recent versions of OMC

### ISSUE THREAD

**Issue by casella** [OpenModelica/OpenModelica#12749]
Consider the following MWE:
```modelica
model TestDirectionalDerivativesFMU
  Real x;
  input Real u;
  output Real y;
equation
  der(x) = -x + u;
  y = 2*x;
end TestDirectionalDerivativesFMU;
```
If I set `d=-disableDirectionalDerivatives` in Tools | Options | Simulation | Additional Translation Flags and then export the system as an FMU, I get the following errors when compiling the C code:
```
D:/Temp/OMEdit/TestDirectionalDerivativesFMUe46a/TestDirectionalDerivativesFMU.fmutmp/sources/TestDirectionalDerivativesFMU.c:281:4: error: incompatible function pointer types initializing 'int (*)(void *, threadData_t *, ANALYTIC_JACOBIAN *)' (aka 'int (*)(void *, struct threadData_s *, struct ANALYTIC_JACOBIAN *)') with an expression of type 'int (DATA *, threadData_t *, ANALYTIC_JACOBIAN *)' (aka 'int (struct DATA *, struct threadData_s *, struct ANALYTIC_JACOBIAN *)') [-Wincompatible-function-pointer-types] 
  281 |    TestDirectionalDerivativesFMU_initialAnalyticJacobianFMIDER, 
      |    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
D:/Temp/OMEdit/TestDirectionalDerivativesFMUe46a/TestDirectionalDerivativesFMU.fmutmp/sources/TestDirectionalDerivativesFMU.c:284:4: error: incompatible function pointer types initializing 'int (*)(void *, threadData_t *, ANALYTIC_JACOBIAN *)' (aka 'int (*)(void *, struct threadData_s *, struct ANALYTIC_JACOBIAN *)') with an expression of type 'int (DATA *, threadData_t *, ANALYTIC_JACOBIAN *)' (aka 'int (struct DATA *, struct threadData_s *, struct ANALYTIC_JACOBIAN *)') [-Wincompatible-function-pointer-types] 
  284 |    TestDirectionalDerivativesFMU_initialAnalyticJacobianFMIDERINIT, 
      |    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
2 errors generated. 
```
When using an old version of OMC (1.20.0-dev-281) the problem did not occur, so it was probably a regression added at some point.  N

I also tried adding `--generateSymbolicJacobian`, but I have the same problem.

I am not sure if the problem is in the backend or in later stages. Maybe it's just an FMI issue. 

@phannebohm, @kabdelhak, @AnHeuermann, @arun3688, can you please have a look? This is critical for our work on the modelling of gas transportation networks.

Keeping @sergio-milo in the loop

**Comment by casella** [comment]
If gcc is used instead of clang, the problem disappears (!)

@adrpo, @AnHeuermann, @sjoelund, we should investigate why this happens.

**Comment by casella** [comment]
If this is an easy fix, we should back-port it to 1.23.2

**Comment by bilderbuchi** [comment]
> If gcc is used instead of clang, the problem disappears (!)

Are you sure the problem disappears, or is maybe just demoted to a compiler warning in gcc? 

incompatible-function-pointer-types became an error instead of a warning in Clang 16 -- what's the Clang version in 1.20.0-dev-281?

**Comment by sergio-milo** [comment]
I have OMC 1.23.1, when using **C: gcc, CXX: g++**, I get:

```
[15] 11:55:23 Translation Errore
Internal error IndexReduction.pantelidesIndexReduction failed! System is structurally singular and cannot be handled because the number of unassigned equations is larger than the number of states. Use -d=bltdump to get more information.

[16] 11:55:23 Translation Errore
Internal error Transformation Module PFPlusExt index Reduction Method Pantelides failed!

[17] 11:55:23 Translation Errore
[C:/OM123/OM64bit/OMCompiler/Compiler/BackEnd/SymbolicJacobian.mo: 2348:10-2348:88]: Internal error function optimizeJacobianMatrix failed

[18] 11:55:23 Translation Errore
[C:/OM123/OM64bit/OMCompiler/Compiler/BackEnd/SymbolicJacobian.mo: 2265:9-2265:79]: Internal error function createJacobian failed

[19] 11:55:23 Translation Errore
[C:/OM123/OM64bit/OMCompiler/Compiler/BackEnd/SymbolicJacobian.mo: 1963:3-1963:101]: Internal error function createFMIModelDerivativesForInitialization failed

[20] 11:55:23 Scripting Notification
The FMU is generated at C:/Users/giose/Desktop/temp/SNAM.Network.fmu.
```

and the FMU is generated and it works.

Instead when using **C: clang, CXX: clang++**, I get additional errors and the FMU is not generated:

```
[14] 12:32:29 Translation Errore
Internal error IndexReduction.pantelidesIndexReduction failed! System is structurally singular and cannot be handled because the number of unassigned equations is larger than the number of states. Use -d=bltdump to get more information.

[15] 12:32:29 Translation Errore
Internal error Transformation Module PFPlusExt index Reduction Method Pantelides failed!

[16] 12:32:29 Translation Errore
[C:/OM123/OM64bit/OMCompiler/Compiler/BackEnd/SymbolicJacobian.mo: 2348:10-2348:88]: Internal error function optimizeJacobianMatrix failed

[17] 12:32:29 Translation Errore
[C:/OM123/OM64bit/OMCompiler/Compiler/BackEnd/SymbolicJacobian.mo: 2265:9-2265:79]: Internal error function createJacobian failed

[18] 12:32:29 Translation Errore
[C:/OM123/OM64bit/OMCompiler/Compiler/BackEnd/SymbolicJacobian.mo: 1963:3-1963:101]: Internal error function createFMIModelDerivativesForInitialization failed

[19] 12:32:29 Translation Errore
Error building simulator. Build log: cmd: cd "Network.fmutmp/sources/" && mkdir build_cmake_dynamic && cd build_cmake_dynamic && cmake -G "MSYS Makefiles" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_C_COMPILER="clang" -DCMAKE_CXX_COMPILER="clang++" .. && cmake --build . --parallel  --target install && cd .. && rm -rf build_cmake_dynamic
-- The C compiler identification is Clang 17.0.6
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/OpenModelica1.23.1-64bit/tools/msys/ucrt64/bin/clang.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- FMI2 include directory: C:/Program Files/OpenModelica1.23.1-64bit/include/omc/c/fmi
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Building for FMI platform win64
-- Install directory: C:/Users/giose/AppData/Local/Temp/OpenModelica/OMEdit/Network8142/Network.fmutmp/sources/../binaries/win64
-- Linking C:/Program Files/OpenModelica1.23.1-64bit/lib/omc/libModelicaStandardTables.a
-- Linking C:/Program Files/OpenModelica1.23.1-64bit/lib/omc/libModelicaIO.a
-- Linking C:/Program Files/OpenModelica1.23.1-64bit/lib/omc/libModelicaMatIO.a
-- Linking C:/Program Files/OpenModelica1.23.1-64bit/lib/omc/libzlib.a
-- CVODE: Not linked
-- Not using FMI2_FUNCTION_PREFIX
-- Installing dynamic dependencies from list: C:/Program Files/OpenModelica1.23.1-64bit/lib/omc/libModelicaStandardTables.a;C:/Program Files/OpenModelica1.23.1-64bit/lib/omc/libModelicaIO.a;C:/Program Files/OpenModelica1.23.1-64bit/lib/omc/libModelicaMatIO.a;C:/Program Files/OpenModelica1.23.1-64bit/lib/omc/libzlib.a
-- Configuring done (3.7s)
-- Generating done (0.1s)
CMake Warning:
  Manually-specified variables were not used by the project:     CMAKE_CXX_COMPILER 
-- Build files have been written to: C:/Users/giose/AppData/Local/Temp/OpenModelica/OMEdit/Network8142/Network.fmutmp/sources/build_cmake_dynamic
[  0%] Building C object CMakeFiles/Network.dir/external_solvers/dgemm.c.obj 
...
...
C:/Users/giose/AppData/Local/Temp/OpenModelica/OMEdit/Network8142/Network.fmutmp/sources/Network.c:186379:4: error: incompatible function pointer types initializing 'int (*)(void *, threadData_t *, ANALYTIC_JACOBIAN *)' (aka 'int (*)(void *, struct threadData_s *, struct ANALYTIC_JACOBIAN *)') with an expression of type 'int (DATA *, threadData_t *, ANALYTIC_JACOBIAN *)' (aka 'int (struct DATA *, struct threadData_s *, struct ANALYTIC_JACOBIAN *)') [-Wincompatible-function-pointer-types] 
 186379 |    Network_initialAnalyticJacobianFMIDER, 
        |    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
[ 84%] Building C object CMakeFiles/Network.dir/Network_08bnd_part31.c.obj 
1 error generated. 
[ 85%] Building C object CMakeFiles/Network.dir/Network_08bnd_part32.c.obj 

```

**Comment by casella** [comment]
> incompatible-function-pointer-types [became an error instead of a warning](https://releases.llvm.org/16.0.0/tools/clang/docs/ReleaseNotes.html#potentially-breaking-changes) in Clang 16 -- what's the Clang version in 1.20.0-dev-281?

I think this might have happened when we updated the Windows Linux environment from MSYS2/MINGW64 to MSYS2/UCRT64, see #10939

The clang version in the latest windows nightly build is 17.0.6. I'm not sure which one it was in 1.20.0-dev-281, I should uninstall and reinstall to check, but given that clang 1.16.0 was released Mar 2023 and omc 1.20.0 was released July 2022, that pretty much explains it.

In any case, it is pretty clear to me that the generated code for directional derivatives is OK (the FMI works as expected) but lacks some explicit casts (or better type definitions) that had been optional in the past, but are now mandatory, so we should fix them.

**Comment by bilderbuchi** [comment]
> In any case, it is pretty clear to me that the generated code for directional derivatives is OK (the FMI works as expected) but lacks some explicit casts (or better type definitions) that had been optional in the past, but are now mandatory, so we should fix them.

If I understood a bug report I read correctly (but C is not my forte), the thing the warning warns about is always Undefined Behaviour, but sometimes it works as expected despite that.

**Comment by casella** [comment]
It is also weird that you get backend errors about Pantelides method on such a stupid ODE example, which is obviously index 1

**Comment by icupeiro** [comment]
hey there,

I was hoping to allocate some time to open this issue with a minimal example, but I see it was already opened. The model I prepared is also quite simple. A heat capacitor connect to a heat flux input and disturbed by a sinusoidal ambient temperature connected through a resistance.

```
model MinimalExample
  input Modelica.Units.SI.HeatFlowRate Q;

  Modelica.Units.SI.Temperature TAmb;


  Modelica.Thermal.HeatTransfer.Components.HeatCapacitor heatCapacitor(C=1e6)
    annotation (Placement(transformation(extent={{-10,2},{10,22}})));
  Modelica.Thermal.HeatTransfer.Components.ThermalResistor thermalResistor(R=1e-2)
    annotation (Placement(transformation(extent={{-40,-30},{-20,-10}})));
  Modelica.Thermal.HeatTransfer.Sources.PrescribedHeatFlow prescribedHeatFlow
    annotation (Placement(transformation(extent={{-60,10},{-40,30}})));
  Modelica.Thermal.HeatTransfer.Sources.PrescribedTemperature
    prescribedTemperature
    annotation (Placement(transformation(extent={{-80,-30},{-60,-10}})));
equation 

  TAmb = 293.15 + 10*sin(2*Modelica.Constants.pi/86400*time);
  prescribedTemperature.T = TAmb;
  prescribedHeatFlow.Q_flow = Q;

  connect(thermalResistor.port_b, heatCapacitor.port)
    annotation (Line(points={{-20,-20},{0,-20},{0,2}}, color={191,0,0}));
  connect(prescribedTemperature.port, thermalResistor.port_a)
    annotation (Line(points={{-60,-20},{-40,-20}}, color={191,0,0}));
  connect(prescribedHeatFlow.port, heatCapacitor.port) annotation (Line(points={
          {-40,20},{-16,20},{-16,-2},{0,-2},{0,2}}, color={191,0,0}));
end MinimalExample;
```

I can see the following error in the static.log file in the resources folder inside the FMU when activating `setDebugFlags("-disableDirectionalDerivatives")`

```
-- The C compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- FMI2 include directory: /usr/bin/../include/omc/c/fmi
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Building for FMI platform linux64
-- Install directory: /tmp/OpenModelica_iago/OMEdit/MinimalExample/MinimalExample.fmutmp/sources/../binaries/linux64
-- CVODE: Not linked
-- Not using FMI2_FUNCTION_PREFIX
-- Installing dynamic dependencies from list: 
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/OpenModelica_iago/OMEdit/MinimalExample/MinimalExample.fmutmp/sources/build_cmake_static
[  2%] Building C object CMakeFiles/MinimalExample.dir/gc/memory_pool.c.o
[  2%] Building C object CMakeFiles/MinimalExample.dir/gc/omc_gc.c.o
[  4%] Building C object CMakeFiles/MinimalExample.dir/math-support/pivot.c.o
[  5%] Building C object CMakeFiles/MinimalExample.dir/meta/meta_modelica_catch.c.o
[  7%] Building C object CMakeFiles/MinimalExample.dir/simulation/omc_simulation_util.c.o
[ 10%] Building C object CMakeFiles/MinimalExample.dir/simulation/jacobian_util.c.o
[ 10%] Building C object CMakeFiles/MinimalExample.dir/simulation/options.c.o
[ 13%] Building C object CMakeFiles/MinimalExample.dir/simulation/simulation_omc_assert.c.o
[ 13%] Building C object CMakeFiles/MinimalExample.dir/simulation/simulation_info_json.c.o
[ 14%] Building C object CMakeFiles/MinimalExample.dir/simulation/solver/delay.c.o
[ 16%] Building C object CMakeFiles/MinimalExample.dir/simulation/solver/fmi_events.c.o
[ 17%] Building C object CMakeFiles/MinimalExample.dir/simulation/solver/model_help.c.o
[ 19%] Building C object CMakeFiles/MinimalExample.dir/simulation/solver/initialization/initialization.c.o
[ 20%] Building C object CMakeFiles/MinimalExample.dir/simulation/solver/omc_math.c.o
[ 22%] Building C object CMakeFiles/MinimalExample.dir/util/base_array.c.o
[ 23%] Building C object CMakeFiles/MinimalExample.dir/util/boolean_array.c.o
[ 25%] Building C object CMakeFiles/MinimalExample.dir/util/context.c.o
[ 26%] Building C object CMakeFiles/MinimalExample.dir/util/ModelicaUtilities.c.o
[ 28%] Building C object CMakeFiles/MinimalExample.dir/simulation/solver/spatialDistribution.c.o
[ 29%] Building C object CMakeFiles/MinimalExample.dir/simulation/solver/synchronous.c.o
[ 31%] Building C object CMakeFiles/MinimalExample.dir/simulation/solver/stateset.c.o
[ 32%] Building C object CMakeFiles/MinimalExample.dir/util/division.c.o
[ 34%] Building C object CMakeFiles/MinimalExample.dir/util/doubleEndedList.c.o
[ 35%] Building C object CMakeFiles/MinimalExample.dir/util/index_spec.c.o
[ 37%] Building C object CMakeFiles/MinimalExample.dir/util/list.c.o
[ 40%] Building C object CMakeFiles/MinimalExample.dir/util/generic_array.c.o
[ 40%] Building C object CMakeFiles/MinimalExample.dir/util/integer_array.c.o
[ 41%] Building C object CMakeFiles/MinimalExample.dir/util/modelica_string.c.o
[ 43%] Building C object CMakeFiles/MinimalExample.dir/util/modelica_string_lit.c.o
[ 44%] Building C object CMakeFiles/MinimalExample.dir/util/omc_error.c.o
[ 46%] Building C object CMakeFiles/MinimalExample.dir/util/omc_file.c.o
[ 49%] Building C object CMakeFiles/MinimalExample.dir/util/omc_mmap.c.o
[ 49%] Building C object CMakeFiles/MinimalExample.dir/util/omc_init.c.o
[ 50%] Building C object CMakeFiles/MinimalExample.dir/util/omc_numbers.c.o
[ 52%] Building C object CMakeFiles/MinimalExample.dir/util/parallel_helper.c.o
[ 53%] Building C object CMakeFiles/MinimalExample.dir/util/omc_msvc.c.o
[ 56%] Building C object CMakeFiles/MinimalExample.dir/util/rational.c.o
[ 56%] Building C object CMakeFiles/MinimalExample.dir/util/real_array.c.o
[ 58%] Building C object CMakeFiles/MinimalExample.dir/util/ringbuffer.c.o
[ 59%] Building C object CMakeFiles/MinimalExample.dir/util/simulation_options.c.o
[ 61%] Building C object CMakeFiles/MinimalExample.dir/util/string_array.c.o
[ 62%] Building C object CMakeFiles/MinimalExample.dir/util/utility.c.o
[ 64%] Building C object CMakeFiles/MinimalExample.dir/util/varinfo.c.o
[ 65%] Building C object CMakeFiles/MinimalExample.dir/MinimalExample.c.o
[ 67%] Building C object CMakeFiles/MinimalExample.dir/MinimalExample_01exo.c.o
[ 68%] Building C object CMakeFiles/MinimalExample.dir/MinimalExample_02nls.c.o
[ 70%] Building C object CMakeFiles/MinimalExample.dir/MinimalExample_03lsy.c.o
[ 71%] Building C object CMakeFiles/MinimalExample.dir/MinimalExample_04set.c.o
[ 73%] Building C object CMakeFiles/MinimalExample.dir/MinimalExample_05evt.c.o
[ 74%] Building C object CMakeFiles/MinimalExample.dir/MinimalExample_06inz.c.o
[ 76%] Building C object CMakeFiles/MinimalExample.dir/MinimalExample_07dly.c.o
**/tmp/OpenModelica_iago/OMEdit/MinimalExample/MinimalExample.fmutmp/sources/MinimalExample.c:417:4: warning: initialization of 'int (*)(void *, threadData_t *, ANALYTIC_JACOBIAN *)' {aka 'int (*)(void *, struct threadData_s *, ANALYTIC_JACOBIAN *)'} from incompatible pointer type 'int (*)(DATA *, threadData_t *, ANALYTIC_JACOBIAN *)' {aka 'int (*)(struct DATA *, struct threadData_s *, ANALYTIC_JACOBIAN *)'} [-Wincompatible-pointer-types]
  417 |    MinimalExample_read_input_fmu,
      |    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~              
/tmp/OpenModelica_iago/OMEdit/MinimalExample/MinimalExample.fmutmp/sources/MinimalExample.c:417:4: note: (near initialization for 'MinimalExample_callback.initialPartialFMIDER')
/tmp/OpenModelica_iago/OMEdit/MinimalExample/MinimalExample.fmutmp/sources/MinimalExample.c:420:4: warning: initialization of 'int (*)(void *, threadData_t *, ANALYTIC_JACOBIAN *)' {aka 'int (*)(void *, struct threadData_s *, ANALYTIC_JACOBIAN *)'} from incompatible pointer type 'int (*)(DATA *, threadData_t *, ANALYTIC_JACOBIAN *)' {aka 'int (*)(struct DATA *, struct threadData_s *, ANALYTIC_JACOBIAN *)'} [-Wincompatible-pointer-types]
  420 |    MinimalExample_INDEX_JAC_FMIDER,
      |    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                
/tmp/OpenModelica_iago/OMEdit/MinimalExample/MinimalExample.fmutmp/sources/MinimalExample.c:420:4: note: (near initialization for 'MinimalExample_callback.initialPartialFMIDERINIT')**
[ 77%] Building C object CMakeFiles/MinimalExample.dir/MinimalExample_08bnd.c.o
[ 79%] Building C object CMakeFiles/MinimalExample.dir/MinimalExample_09alg.c.o
[ 80%] Building C object CMakeFiles/MinimalExample.dir/MinimalExample_10asr.c.o
[ 82%] Building C object CMakeFiles/MinimalExample.dir/MinimalExample_11mix.c.o
[ 83%] Building C object CMakeFiles/MinimalExample.dir/MinimalExample_12jac.c.o
[ 85%] Building C object CMakeFiles/MinimalExample.dir/MinimalExample_13opt.c.o
[ 86%] Building C object CMakeFiles/MinimalExample.dir/MinimalExample_14lnz.c.o
[ 88%] Building C object CMakeFiles/MinimalExample.dir/MinimalExample_15syn.c.o
[ 89%] Building C object CMakeFiles/MinimalExample.dir/MinimalExample_17inl.c.o
[ 91%] Building C object CMakeFiles/MinimalExample.dir/MinimalExample_16dae.c.o
[ 92%] Building C object CMakeFiles/MinimalExample.dir/MinimalExample_18spd.c.o
[ 94%] Building C object CMakeFiles/MinimalExample.dir/MinimalExample_functions.c.o
[ 95%] Building C object CMakeFiles/MinimalExample.dir/MinimalExample_FMU.c.o
[ 97%] Building C object CMakeFiles/MinimalExample.dir/MinimalExample_init_fmu.c.o
[ 98%] Building C object CMakeFiles/MinimalExample.dir/MinimalExample_records.c.o
[100%] Linking C shared library MinimalExample.so
[100%] Built target MinimalExample
Install the project...
-- Install configuration: "Debug"
-- Installing: /tmp/OpenModelica_iago/OMEdit/MinimalExample/MinimalExample.fmutmp/sources/../binaries/linux64/MinimalExample.so
-- Set runtime path of "/tmp/OpenModelica_iago/OMEdit/MinimalExample/MinimalExample.fmutmp/sources/../binaries/linux64/MinimalExample.so" to "$ORIGIN"
```

This happens both for clang and gcc as compilers
I am using OpenModelica 1.24.0~dev-208-g5ddb9ff (nightly build) in Linux Mint 21.2 (Victoria)

Is there any workaround at the moment?

**Comment by casella** [comment]
@AnHeuermann, @arun3688, could you please have a look and give some feedback about this issue?

**Comment by icupeiro** [comment]
Hello,

Is there a quick workaround we could do while we wait for this issue to be solved?

**Comment by arun3688** [comment]
@icupeiro @casella I did a quick test and it works for me see the below mos script.

a.mos
```
setCommandLineOptions("-d=-disableDirectionalDerivatives,fmuExperimental");
getErrorString();

loadString("
  model TestDirectionalDerivativesFMU
    Real x;
    input Real u;
    output Real y;
  equation
    der(x) = -x + u;
    y = 2*x;
  end TestDirectionalDerivativesFMU;
"); getErrorString();


buildModelFMU(TestDirectionalDerivativesFMU); getErrorString();
```

running the above mos script with enabling `-d=-disableDirectionalDerivatives` works fine for me, i hope this issue should be resolved with the latest nightly builds please test it

**Comment by icupeiro** [comment]
The script seems to work for me only if I work in root mode. In user mode I get the same error as before (latest nightly build 1.24.0~dev-242-g43d5150)

**Comment by icupeiro** [comment]
Nope, from a Linux Mint OS

**Comment by casella** [comment]
@arun3688 maybe you can get a look at this issue and figure out what goes wrong?

**Comment by FabiJa** [comment]
I think I have a similar problem with Windows + OM 1.23.1 and the simple model:
```
model vdp
  Real x1(start=0, fixed = true);
  Real x2(start=1, fixed = true);
  input Real u(min = -1, max = 1);
equation
  der(x1) = (1-x2^2)*x1 - x2 + u;
  der(x2) = x1;
end vdp;
```
I get similar error messages as above:
```
C:/Users/***/AppData/Local/Temp/OpenModelica/OMEdit/vdpa0fc/vdp.fmutmp/sources/vdp.c:287:4: error: incompatible function pointer types initializing 'int (*)(void *, threadData_t *, ANALYTIC_JACOBIAN *)' (aka 'int (*)(void *, struct threadData_s *, struct ANALYTIC_JACOBIAN *)') with an expression of type 'int (DATA *, threadData_t *, ANALYTIC_JACOBIAN *)' (aka 'int (struct DATA *, struct threadData_s *, struct ANALYTIC_JACOBIAN *)') [-Wincompatible-function-pointer-types] 
  287 |    vdp_initialAnalyticJacobianFMIDER, 
      |    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
C:/Users/***/AppData/Local/Temp/OpenModelica/OMEdit/vdpa0fc/vdp.fmutmp/sources/vdp.c:290:4: error: incompatible function pointer types initializing 'int (*)(void *, threadData_t *, ANALYTIC_JACOBIAN *)' (aka 'int (*)(void *, struct threadData_s *, struct ANALYTIC_JACOBIAN *)') with an expression of type 'int (DATA *, threadData_t *, ANALYTIC_JACOBIAN *)' (aka 'int (struct DATA *, struct threadData_s *, struct ANALYTIC_JACOBIAN *)') [-Wincompatible-function-pointer-types] 
  290 |    vdp_initialAnalyticJacobianFMIDERINIT, 
      |    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
2 errors generated. 
```
What works is to use WSL + OM 1.25dev and use `fmpy` to compile the source code FMU for e.g. Win64.

**Comment by arun3688** [comment]
@FabiJa Could you please download the nightly builds from tomorrow(24-09-2024) and export your model as fmu, I tried to export your model as fmu and it worked fine

![image](https://github.com/user-attachments/assets/d867d0c1-6cc3-42f4-a70e-ef41c1dfe6da)

**Comment by FabiJa** [comment]
Hi @arun3688, do I need a time machine to get this build? ;-) Nevertheless, I tried the most [recent nightly](https://build.openmodelica.org/omc/builds/windows/nightly-builds/64bit/OpenModelica-latest.exe) for Windows I could find and it seems to solve the problem. Thx!

**Comment by arun3688** [comment]
@FabiJa the reason to test the nightly builds from tomorrow(23-09-2024) is because we have improved the fmu export support in `OMEDit`, from the above image you can see the progress bar indicator and other building steps which you cannot currently see it now

**Comment by casella** [comment]
> Hi @arun3688, do I need a time machine to get this build? ;

Only some patience 😛

**Comment by FabiJa** [comment]
With the current nightly `v1.25.0-dev-31-ge9e3dc1832 (64-bit)` I again get errors:
```
C:/Users/***/AppData/Local/Temp/OpenModelica/OMEdit/vdpa0fc/vdp.fmutmp/sources/vdp.c:287:4: error: incompatible function pointer types initializing 'int (*)(void *, threadData_t *, ANALYTIC_JACOBIAN *)' (aka 'int (*)(void *, struct threadData_s *, struct ANALYTIC_JACOBIAN *)') with an expression of type 'int (DATA *, threadData_t *, ANALYTIC_JACOBIAN *)' (aka 'int (struct DATA *, struct threadData_s *, struct ANALYTIC_JACOBIAN *)') [-Wincompatible-function-pointer-types]
  287 |    vdp_initialAnalyticJacobianFMIDER,
      |    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/Users/***/AppData/Local/Temp/OpenModelica/OMEdit/vdpa0fc/vdp.fmutmp/sources/vdp.c:290:4: error: incompatible function pointer types initializing 'int (*)(void *, threadData_t *, ANALYTIC_JACOBIAN *)' (aka 'int (*)(void *, struct threadData_s *, struct ANALYTIC_JACOBIAN *)') with an expression of type 'int (DATA *, threadData_t *, ANALYTIC_JACOBIAN *)' (aka 'int (struct DATA *, struct threadData_s *, struct ANALYTIC_JACOBIAN *)') [-Wincompatible-function-pointer-types]
  290 |    vdp_initialAnalyticJacobianFMIDERINIT,
      |    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
make[2]: *** [CMakeFiles/vdp.dir/build.make:706: CMakeFiles/vdp.dir/vdp.c.obj] Error 1
make[2]: *** Waiting for unfinished jobs....
```

**Comment by arun3688** [comment]
@FabiJa This is really strange and i don't get any errors see below

![image](https://github.com/user-attachments/assets/c698838a-111e-4f74-ad58-7f8b61f5f772)

i guess `OPENMODELICAHOME` environment is messing with old omc installation i guess, please uninstall all your OpenModelica version and do a clean install and see if that solves

**Comment by FabiJa** [comment]
The older version of OM is uninstalled. Maybe its related to the compiler (setting)?
I will do a restart and see what happens.

**Comment by FabiJa** [comment]
Same result on a newly set-up VM of WIN11 and fresh install of OM nightly on OpenModelica v1.25.0-dev-32-gc296bbf01a (64-bit):
```
C:/Users/***/AppData/Local/Temp/OpenModelica/OMEdit/vdpa0fc/vdp.fmutmp/sources/vdp.c:287:4: error: incompatible function pointer types initializing 'int (*)(void *, threadData_t *, ANALYTIC_JACOBIAN *)' (aka 'int (*)(void *, struct threadData_s *, struct ANALYTIC_JACOBIAN *)') with an expression of type 'int (DATA *, threadData_t *, ANALYTIC_JACOBIAN *)' (aka 'int (struct DATA *, struct threadData_s *, struct ANALYTIC_JACOBIAN *)') [-Wincompatible-function-pointer-types]
  287 |    vdp_initialAnalyticJacobianFMIDER,
      |    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/Users/***/AppData/Local/Temp/OpenModelica/OMEdit/vdpa0fc/vdp.fmutmp/sources/vdp.c:290:4: error: incompatible function pointer types initializing 'int (*)(void *, threadData_t *, ANALYTIC_JACOBIAN *)' (aka 'int (*)(void *, struct threadData_s *, struct ANALYTIC_JACOBIAN *)') with an expression of type 'int (DATA *, threadData_t *, ANALYTIC_JACOBIAN *)' (aka 'int (struct DATA *, struct threadData_s *, struct ANALYTIC_JACOBIAN *)') [-Wincompatible-function-pointer-types]
  290 |    vdp_initialAnalyticJacobianFMIDERINIT,
      |    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
make[2]: *** [CMakeFiles/vdp.dir/build.make:678: CMakeFiles/vdp.dir/vdp.c.obj] Error 1
```

**Comment by FabiJa** [comment]
@casella Seems to be fixed in 1.24.0, or?

**Comment by casella** [comment]
@FabJa I no longer get the original problem I posted when I use v1.25.0-dev-138-g4bd69db6a1. I am not sure it already worked with 1.24.0. Did you try that?

**Comment by casella** [comment]
I'm closing this for 1.25.0. @FabiJa, please comment if it works for you on 1.24.0, in which case I can update the milestone accordingly.

**Comment by FabiJa** [comment]
> I'm closing this for 1.25.0. @FabiJa, please comment if it works for you on 1.24.0, in which case I can update the milestone accordingly.

Yes, I tested the export with subsequent simulation with `fmpy` of my VanDerPol example (see above) successfully with 1.24.0 (Windows) and `-d=-disableDirectionalDerivatives`. Flag in the ModelExchange part of the `modelDescription.xml` is `providesDirectionalDerivative="true"`.
