### ISSUE TITLE
OpenModelica fails to build with boost-1.87+

### ISSUE THREAD

**Issue by yurivict** [OpenModelica/OpenModelica#13682]
configure prints this:
```
/usr/ports/science/openmodelica/work/OpenModelica-1.24.5/OMCompiler/SimulationRuntime/cpp/SimCoreFactory/OMCFactory/OMCFactory.cpp:85:16: error: no type named 'io_service' in namespace 'boost::asio'
   85 |   boost::asio::io_service _ios;
      |   ~~~~~~~~~~~~~^
/usr/ports/science/openmodelica/work/OpenModelica-1.24.5/OMCompiler/SimulationRuntime/cpp/SimCoreFactory/OMCFactory/OMCFactory.cpp:37:17: error: incompatible pointer types assigning to 'Logger *' from 'LoggerXMLTCP *'
   37 |     _instance = new LoggerXMLTCP(host, port, logSettings);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/ports/science/openmodelica/work/OpenModelica-1.24.5/OMCompiler/SimulationRuntime/cpp/SimCoreFactory/OMCFactory/OMCFactory.cpp:43:43: error: no member named 'from_string' in 'boost::asio::ip::address'
   43 |     , _endpoint(boost::asio::ip::address::from_string(host), port)
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^
/usr/ports/science/openmodelica/work/OpenModelica-1.24.5/OMCompiler/SimulationRuntime/cpp/SimCoreFactory/OMCFactory/OMCFactory.cpp:57:16: error: cannot initialize object parameter of type 'LoggerXML' with an expression of type 'LoggerXMLTCP'
   57 |     LoggerXML::writeInternal(msg, cat, lvl, ls);
      |                ^~~~~~~~~~~~~
4 errors generated.
```

The class boost::asio::io_service was deprecated in Boost.

Could you please make a release with the fix?

Version: 1.24.5

**Comment by perost** [comment]
Fix ported from master to the 1.24 branch with #13683.

**Comment by casella** [comment]
@yurivict we are going to release 1.25.0-beta.1 this week, also including that fix, would that be OK?

**Comment by yurivict** [comment]
It's fine, thank you.
I added the patch to the openmodelica port so that it builds now.
